### PR TITLE
Resolve variables before polling system

### LINKED ISSUE #4885: os-distribution
```
$ opam --version
2.1.0
```
opam has a global configuration variable `os-distribution`, but this variable seems to be ignored at least in most (if not all) cases, instead trying to guess the its value dynamically by checking which one of the two commands `brew` or `port` (in this order) is executable.

Here is my global config: 
```
$ opam var | grep os
os                macos             # Inferred from system
os-distribution   macports          # Set through 'opam config set-global'
os-family         bsd               # Set through 'opam config set-global'
os-version        11.6              # Inferred from system
```
However, opam seems to bypass this configuration:
```
$ opam config report | grep system
# system               arch=x86_64 os=macos os-distribution=homebrew os-version=11.6
```
The reason is that (for some reason) I have both `port` and `brew` binaries installed. 
Indeed, removing the executable rights to the `brew` command
```
$ chmod -x /usr/local/bin/brew 
```
fixes the problem:
```
$ opam config report | grep system
# system               arch=x86_64 os=macos os-distribution=macports os-version=11.6
```
But I consider this to be a bug since the global `os-distribution` variable seems to be always overriden.  

As a result,  `opam` 
  - always wants to install external dependencies with `brew`, which I must refuse.
  - fails to install most `conf-*` packages even when these are correctly installed with macports.

My only solution is thus to make `brew` non-executable.

### PR DESCRIPTION
**Pull request by rjbou**
fix #4885

### CODE REVIEW

File: src/state/opamSysInteract.ml [hunk 1]
```diff
@@ -97,41 +97,37 @@ type families =
   | Suse
 
 (* System status *)
-let family =
-  let family = lazy (
-    match OpamSysPoll.os_family () with
-    | None ->
+let family ?env () =
```
Comment (kit-ty-kate) [inline src/state/opamSysInteract.ml:100]:
```suggestion
let family ~env () =
```
I’d rather have the new parameter as non-optional to avoid easy tricky bugs when used

File: src/state/opamSwitchState.ml [hunk 2]
```diff
@@ -738,7 +740,7 @@ let depexts st nv =
 
 let depexts_status_of_packages st set =
   depexts_status_of_packages_raw st.switch_global.config st.switch_config set
-    ~depexts:(depexts st)
+   ~env:st.switch_global.global_variables ~depexts:(depexts st)
```
Comment (kit-ty-kate) [inline src/state/opamSwitchState.ml:743]:
```suggestion
    ~env:st.switch_global.global_variables ~depexts:(depexts st)
```
just a small nitpick (missing space)

File: src/state/opamSysInteract.ml (hunk 1 above)
Comment (kit-ty-kate) [reply src/state/opamSysInteract.ml]: (The env parameter is also present at several other places and the code currently doesn’t compile with just this suggestion)

File: src/client/opamCommands.ml [hunk 3]
```diff
@@ -1307,90 +1302,94 @@ let config cli =
...
-          let process nv =
-            try
-              let conf = OpamSwitchState.package_config state nv.name in
-              let bindings =
-                let f (name, value) =
-                  (OpamVariable.Full.create nv.name name,
-                   OpamVariable.string_of_variable_contents value)
+          match OpamStateConfig.get_switch_opt () with
+          | None -> print "current-switch" "%s" "non set"
+          | Some switch ->
```
Comment (rjbou) [inline src/client/opamCommands.ml:1307]: it's the only addition, rest is indentation

File: src/state/opamSysPoll.ml [hunk 4]
```diff
@@ -143,13 +151,16 @@ let os_family_lazy = lazy (
...
 )
-let os_family () = Lazy.force os_family_lazy
+let os_family = syspoll "os-family" os_family_lazy
 
 let variables =
   List.map
     (fun (n, v) ->
        OpamVariable.of_string n,
-       lazy (Lazy.force v >>| fun v -> OpamTypes.S v))
+       lazy (try Lazy.force v >>| fun v -> OpamTypes.S v
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/state/opamSysPoll.ml:160]: spliited in #5199

File: src/client/opamCommands.ml (hunk 3 above)
Comment (rjbou) [reply src/client/opamCommands.ml]: split in #5198

File: src/client/opamAction.ml [hunk 5]
```diff
@@ -602,7 +602,10 @@ let make_command st opam ?dir ?text_command (cmd, args) =
     let open OpamStd.Option.Op in
     String.concat " | " [
       OpamVersion.(to_string current);
-      (OpamSysPoll.os () +! "unknown") ^"/"^ (OpamSysPoll.arch () +! "unknown");
+      (let env =st.switch_global.global_variables in
+      Printf.sprintf "%s/%s"
+      (OpamSysPoll.os ~env () +! "unknown")
+      (OpamSysPoll.arch ~env () +! "unknown"));
```
Comment (kit-ty-kate) [inline src/client/opamAction.ml:608]: Reformatting slightly
```suggestion
      (let env = st.switch_global.global_variables in
       Printf.sprintf "%s/%s"
       (OpamSysPoll.os ~env () +! "unknown")
       (OpamSysPoll.arch ~env () +! "unknown"));
```

**Review by kit-ty-kate — APPROVED** [review]
Apart from the minor reformat suggestion, LGTM.

File: src/state/opamSysPoll.ml [hunk 6]
```diff
@@ -22,6 +22,14 @@ let command_output c =
 
 let norm s = if s = "" then None else Some (String.lowercase_ascii s)
 
+let syspoll var laz ?(env=OpamVariable.Map.empty) () =
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/state/opamSysPoll.ml:25]: Indeed, it is more clear

**Comment by rjbou** [comment]
We need the `~env` to specify the environment to look in for variables.

File: src/state/opamSysPoll.ml [hunk 7]
```diff
@@ -10,6 +10,10 @@
 
 open OpamStd.Option.Op
 
+let make_lazy f =
+  let v = Lazy.from_fun f in
+  fun () -> Lazy.force v
+
```
Comment (dra27) [inline src/state/opamSysPoll.ml:16]: Sorry - looking at how it's then gone below, I this could be dropped and just use `Lazy.from_fun` below...

File: src/state/opamSysPoll.ml [hunk 8]
```diff
@@ -142,29 +142,42 @@ let os_family_lazy = lazy (
...
   | _ -> os_distribution ()
-)
-let os_family () = Lazy.force os_family_lazy
+let os_family = make_lazy poll_os_family
 
 let variables =
   List.map
     (fun (n, v) ->
        OpamVariable.of_string n,
        lazy (Lazy.force v >>| fun v -> OpamTypes.S v))
```
Comment (dra27) [inline src/state/opamSysPoll.ml:151]: ...with...
```suggestion
       Lazy.map (Option.map OpamTypes.S))
```
...and...

File: src/state/opamSysPoll.ml [hunk 9]
```diff
@@ -142,29 +142,42 @@ let os_family_lazy = lazy (
...
-      "arch", arch_lazy;
-      "os", os_lazy;
-      "os-distribution", os_distribution_lazy;
-      "os-version", os_version_lazy;
-      "os-family", os_family_lazy;
+      "arch", lazy (arch ());
+      "os", lazy (os ());
+      "os-distribution", lazy (os_distribution ());
+      "os-version", lazy (os_version ());
+      "os-family", lazy (os_family ());
```
Comment (dra27) [inline src/state/opamSysPoll.ml:157]:
```suggestion
      "arch", arch;
      "os", os;
      "os-distribution", os_distribution;
      "os-version", os_version;
      "os-family", os_family;
```

File: src/state/opamSysPoll.ml [hunk 10]
```diff
@@ -142,29 +142,42 @@ let os_family_lazy = lazy (
...
     ]
 
-let cores_lazy = lazy (OpamSystem.cpu_count ())
-let cores () = Lazy.force cores_lazy
+let cores = make_lazy OpamSystem.cpu_count
```
Comment (dra27) [inline src/state/opamSysPoll.ml:160]: OK, maybe `make_lazy` is useful still exactly here :)

File: src/state/opamSysPoll.ml [hunk 11]
```diff
@@ -142,29 +142,42 @@ let os_family_lazy = lazy (
...
+
+(* Exported functions *)
+let resolve_or_poll var poll env =
+  match OpamVariable.Full.read_from_env (OpamVariable.Full.of_string var) with
+  | Some (S c) -> Some c
+  | _ ->
+    match OpamVariable.Map.find_opt (OpamVariable.of_string var) env with
+    | Some (lazy (Some (OpamTypes.S c)), _) -> Some c
+    | _ -> poll ()
```
Comment (dra27) [inline src/state/opamSysPoll.ml:169]:
```suggestion
    | _ -> Lazy.force poll
```

**Review by dra27 — COMMENTED** [review]
A possible further disentangling of laziness!
