### PR TITLE
Var: catch an package not found error and print skipping message

### LINKED ISSUE #5279: Disgraceful error message on `opam var --package=p` when p does not exist.
```
> opam --version 
2.1.2
> opam var --package=fictional
Fatal error:
Not_found
Backtrace:
  Raised at Stdlib__set.Make.max_elt in file "set.ml", line 187, characters 17-32
  Called from OpamPackage.max_version in file "src/format/opamPackage.ml", line 319, characters 16-44
  Called from OpamConfigCommand.list.list_vars in file "src/client/opamConfigCommand.ml", line 33,
  characters 13-47
  Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23
  Called from OpamConfigCommand.list in file "src/client/opamConfigCommand.ml", line 59, characters 26-49
  Called from OpamCommands.var.print_var.(fun) in file "src/client/opamCommands.ml", line 1069, characters
[...]
```

### PR DESCRIPTION
**Pull request by rjbou**
fix #5279 
And remove some dead code

### CODE REVIEW

File: src/client/opamConfigCommand.ml [hunk 1]
```diff
@@ -21,39 +21,36 @@ let list t ns =
...
   if ns = [] then () else
   let list_vars name =
-    if OpamPackage.Name.to_string name = "-" then
-      let conf = t.switch_config in
-      List.map (fun (v,c) ->
-          OpamVariable.Full.global v,
-          OpamVariable.string_of_variable_contents c,
-          "")
-        (conf.OpamFile.Switch_config.variables)
-    else
```
Comment (kit-ty-kate) [inline src/client/opamConfigCommand.ml:31]: Indeed this code never worked. We should probably also remove it from the documentation: https://github.com/ocaml/opam/commit/56e3e6c62e8178d3634c3f083f8b71393340d8e9#diff-e674376a5ba688da9b6f11571be146af2e7bbde7c583630c6e8d4fc15c575035R1013

Comment (rjbou) [reply src/client/opamConfigCommand.ml:31]: updated

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks!
