### PR TITLE
resolve command: don't select directories

### LINKED ISSUE #5585: Permission Denied error
I've ran into this issue on fresh installs in WSL, Ubuntu Hyper-V and now  Endeavour OS (arch). WSL and Hyper-V I never managed to get working. Things were working fine in Endeavour OS, but after rebooting I'm getting this error again. In Ubuntu the error was the same except that path was `/var/lib/git` Any help would be greatly appreciated. I followed the instructions here for all of the installs. https://ocaml.org/docs/up-and-running

report
```
# opam config report
# opam-version         2.1.4 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=endeavouros os-version=rolling
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 11
# repositories         1 (http) (default repo at 7b30d632)
# pinned               0
# current-switch       /home/daoko/projects/ocaml/dream
# read-state           /usr/bin/opam: "create_process" failed on /var/lib/pacman: Permission denied

```
```
opam install ocaml-lsp-server 
Fatal error:
/usr/bin/opam: "create_process" failed on /var/lib/pacman: Permission denied
```

### PR DESCRIPTION
**Pull request by rjbou**
This PR contains 2 different fixes, that can't be split. It fixes #5585, #5650 and partially #5597, as it fixes command resolve that is it happen to be a directory. I also add a test for that, and to have the test working, reftest engine needs a fix. It was keeping duplicated environment variables in environment given as argument to process creation, and it was not expanding `PATH` on variable export.
It also add syntax to declare env vars paths additions `PATH+=path/to` or `PATH=+path/to`, to make it portable between unix & windows (`:` versus `;`).

Todo:
* [x] update changes

### CODE REVIEW

**Review by kit-ty-kate — APPROVED** [review]

File: src/core/opamSystem.ml [hunk 1]
```diff
@@ -488,9 +488,12 @@ let t_resolve_command =
...
       else name
     in
-    let possibles = OpamStd.List.filter_map (fun path ->
-        let candidate = Filename.concat path name in
-        if Sys.file_exists candidate then Some candidate else None) path
+    let possibles =
+      OpamStd.List.filter_map (fun path ->
+          let candidate = Filename.concat path name in
+          if Sys.file_exists candidate && not (Sys.is_directory candidate) then
+            Some candidate else None)
```
Comment (AltGr) [inline src/core/opamSystem.ml:495]: This is slightly redundant, as `Sys.is_directory` will fail if the file doesn't exist
```suggestion
          match Sys.is_directory candidate with
          | false -> Some candidate
          | true -> None
          | exception (Sys_error _) -> None)
```

**Review by AltGr — APPROVED** [review]
Good catch !

File: src/core/opamSystem.ml (hunk 1 above)
Comment (kit-ty-kate) [reply src/core/opamSystem.ml:495]: A more compressed version can be used instead:
```suggestion
          match Sys.is_directory candidate with
          | false -> Some candidate
          | true | exception (Sys_error _) -> None)
```

**Comment by rjbou** [comment]
Removed new test on windows (unix only) until ocaml/dune#8651 is resolved.
