### PR TITLE
Display an appropriate error message when the file given to opam init --config does not exist

### LINKED ISSUE #5971: `OpamDownload` assertion failure is causing  opam-repo-ci builds to fail on arm32-ocaml-4.14
First noticed (afaik) at https://github.com/ocaml/opam-repository/pull/25905#issuecomment-2119010020

The error we're seeing in CI is

```
/home/opam: (run (network host)
                 (shell "opam init --reinit --config .opamrc-sandbox -ni"))
Fatal error:
File "src/repository/opamDownload.ml", line 140, characters 2-8: Assertion failed
"/usr/bin/linux32" "/bin/sh" "-c" "opam init --reinit --config .opamrc-sandbox -ni" failed with exit status 99
```

which can be seen in, e.g., [this CI log](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f4bd28ba789a542ddaadb40512a72c889061cc5e/variant/extras,arm32-ocaml-4.14,multicore-bench.0.1.3)

The failing assertion is at 

https://github.com/ocaml/opam/blob/391333d35bcdc8b55df709b876b8bafcf75f3452/src/repository/opamDownload.ml#L140

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes #5971 

This PR introduces `OpamUrl.kind` which i think is an improvement over `OpamUrl.local_{file,dir}` as way of detecting if a url is local or not. Most functions that use `OpamUrl.local_{file,dir}` already check later if the file exist and fail gracefully so there is no need to check twice.

I opened https://github.com/ocaml/opam/issues/5978 to think about removing `local_{file,dir}` in the future, but for now this would be a fairly intrusive change.

### CODE REVIEW

**Review by rjbou — CHANGES_REQUESTED** [review]
Discussed in dev meeting, it needs more design. At current stage, it is not possible to have a local path that is a vsc.
I've added some `opam init --config` tests

File: src/core/opamUrl.ml [hunk 1]
```diff
@@ -211,20 +211,42 @@ let base_url url =
...
+  | LocalPath
+  | VersionControl of version_control
+  | Http
+  | Ssh
+
+let kind = function
+  | {backend = (#version_control as vcs); _} -> VersionControl vcs
+  | url ->
+    match local_path url, url with
+    | Some _, {backend = `rsync; _} -> LocalPath
```
[the remark this answers is not in the document]
Comment (kit-ty-kate) [reply src/core/opamUrl.ml]: no because there is no guarantee that the files are in the state that you want on disk (it could point to a different branch, be a bare git repo and thus have no files checked-out, …)

File: src/repository/opamDownload.ml [hunk 2]
```diff
@@ -171,16 +171,25 @@ let really_download
...
+    if OpamFilename.equal src dst then Done () else
       (if OpamFilename.exists dst then
          if overwrite then OpamFilename.remove dst else
            OpamSystem.internal_error "The downloaded file will overwrite %s."
              (OpamFilename.to_string dst);
        OpamFilename.copy ~src ~dst;
        Done ())
-  | None ->
+  | VersionControl vcs ->
+    OpamConsole.error_and_exit `Internal_error
```
[the remark this answers is not in the document]
Comment (kit-ty-kate) [reply src/repository/opamDownload.ml]: i strongly think this should be an error

[the remark this answers is not in the document]
Comment (kit-ty-kate) [reply src/repository/opamDownload.ml]: That's outside of the scope of this PR

[the remark this answers is not in the document]
Comment (rjbou) [reply src/repository/opamDownload.ml]: Even if it is outside the scope, it is something that we could discuss, at least to see if it worth opening an issue

File: src/core/opamUrl.ml (hunk 1 above)
[the remark this answers is not in the document]
Comment (rjbou) [reply src/core/opamUrl.ml]: For several functions, we need to have a local path that is a version control. Sometimes we just need to check if it is a local vcs-ed path, sometimes just local path, sometimes local path non vcs-ed.

File: src/repository/opamDownload.ml [hunk 3]
```diff
@@ -229,16 +229,25 @@ let really_download
   Done ()
 
 let download_as ?quiet ?validate ~overwrite ?compress ?checksum url dst =
-  match OpamUrl.local_file url with
-  | Some src ->
-    if src = dst then Done () else
+  match OpamUrl.kind url with
```
Comment (rjbou) [inline src/repository/opamDownload.ml]: This change is not a change related to the PR purpose

File: src/client/opamCommands.ml [hunk 4]
```diff
@@ -131,9 +131,24 @@ let get_init_config ~no_sandboxing ~no_default_config_file ~add_config_file =
...
+              "File does not exist: %s."
+              (OpamUrl.to_string url)
+        | VersionControl _ ->
+          OpamConsole.error_and_exit `Bad_arguments
+            "Version control url not supported for %S"
+            (OpamUrl.to_string url);
+        | Ssh ->
+          OpamConsole.error_and_exit `Bad_arguments
+            "Ssh url is not supported for %S"
+            (OpamUrl.to_string url);
```
Comment (rjbou) [inline src/client/opamCommands.ml]: I think that we should go through the entire list and then fail gracefully with a complete error message. Here, if some have as argument `--config non-existent --config vcs-file --config ssh-file`, they'il need to run opam init 3 times to remove all errors.

Comment (rjbou) [reply src/client/opamCommands.ml]: At the moment, parsing failure are reported as is
```
$ opam init --config /tmp/parse-error
Configuring from /tmp/parse-error and then from built-in defaults.
[ERROR] Error in configuration file, fix it, use '--no-opamrc', or check your '--config FILE' arguments:
At /tmp/t:1:136-1:137::
Parse error
```
Do we want to handle more gracefully that in that PR ?

Comment (rjbou) [inline src/client/opamCommands.ml]: It is possible to factorise these cases
```suggestion
        | VersionControl _ | Ssh as kind ->
          OpamConsole.error_and_exit `Bad_arguments
            "%s url not supported for %S"
            (OpamUrl.string_of_kind kind)
            (OpamUrl.to_string url);
```

File: src/repository/opamDownload.ml (hunk 2 above)
[the remark this answers is not in the document]
Comment (rjbou) [reply src/repository/opamDownload.ml]: I may have put my comment not in the good place, cf comment in https://github.com/ocaml/opam/pull/5979#discussion_r2547210374.

**Review by rjbou — COMMENTED** [review]
The purpose of the PR and the general way to do it looks good to me.
However, i have several comments.
On the main topic of this PR:
* should we require that all config files are good, or should we skip the ones that are not compliant (bc not found, or backend, or even parsing failures). Currently, parsing errors are erroring at the first failure (related to comment XXX)
* at the moment, parsing failure are reported as is. Do we want to handle more gracefully that in that PR ? 
```
$ opam init --config /tmp/parse-error
Configuring from /tmp/parse-error and then from built-in defaults.
[ERROR] Error in configuration file, fix it, use '--no-opamrc', or check your '--config FILE' arguments:
At /tmp/t:1:136-1:137::
Parse error
```

On the addition of the type `OpamUrl.kind`.
> I opened #5978 to think about removing local_{file,dir} in the future, but for now this would be a fairly intrusive change.

I don't agree. I had to make those changes to be able to precise what are the needs of the type (https://github.com/ocaml/opam/pull/5979#discussion_r2547135194) and confirm the intuition i had.
Having a first PR that adds this type and use it through the codebase without `local_file` and `local_dir` will permit us to refine its definition and usage. Then, we'll be able to use it directly in this PR.
I have a dirty/draft local branch with it, and what i saw is having this type helps to have a more fine grained control (checks) and information (when reading code) about what we expect from those files/directories.

File: src/client/opamCommands.ml (hunk 4 above)
Comment (kit-ty-kate) [reply src/client/opamCommands.ml]: I don't think this is worth spending the time to design this just to support such a niche corner-case

File: src/core/opamUrl.ml (hunk 1 above)
[the remark this answers is not in the document]
Comment (kit-ty-kate) [reply src/core/opamUrl.ml]: The problem with local VCS paths, is that there are no telling that a path to a file is the correct one. Given that we do not know the current branch of whatever is checked-out locally, or even if it is checked-out at all (e.g. bare git repositories)

File: src/repository/opamDownload.ml (hunk 3 above)
Comment (kit-ty-kate) [reply src/repository/opamDownload.ml]: Fair enough, i removed that commit

File: tests/reftests/init.test [hunk 5]
```diff
@@ -303,3 +303,66 @@ wrap-remove-commands: ["%{hooks}%/sandbox.sh" "remove"] {os = "linux" | os = "ma
...
+# Return code 2 #
+### :III:d:5: Non existant distant VCS file
+### rm -rf $OPAMROOT
+### opam init --bypass-checks --bare --no-setup --config git+file://som.e/distant/config
+[ERROR] Version control url not supported for "git+file://som.e/distant/config"
+# Return code 2 #
+### :II:d:1: Non existant http file
+### rm -rf $OPAMROOT
+### opam --version >$ OPAMVERSION
+### opam init --bypass-checks --bare --no-setup --config http://som.e/url/to/config | sed-cmd curl | "${OPAMVERSION}" -> "current" | "[^ ]*build_[^ ]*\.part" -> file.part
```
Comment (kit-ty-kate) [inline tests/reftests/init.test]:
```suggestion
### opam init --bypass-checks --bare --no-setup --config http://som.e/url/to/config | sed-cmd curl | "${OPAMVERSION}" -> "current" | "[^ ]*\.part" -> file.part
```

File: src/client/opamCommands.ml (hunk 4 above)
Comment (rjbou) [reply src/client/opamCommands.ml]: Fair enough. Opened #6814 to track it.

File: master_changes.md [hunk 6]
```diff
@@ -18,6 +18,7 @@ users)
 ## Plugins
 
 ## Init
+  * Display an appropriate error message when the file given to `opam init --config` does not exist or is in a VCS [#5979 @kit-ty-kate - fix #5971]
```
Comment (rjbou) [inline master_changes.md]:
```suggestion
  * ✘ Display an appropriate error message when the file given to `opam init --config` does not exist or is in a VCS. This changes the behaviour for VCS local urls that was previously retrieved. [#5979 @kit-ty-kate - fix #5971]
```

**Review by rjbou — APPROVED** [review]
I've updated the PR with some tests (several errors and parsing errors) and fixed their numbering, and removed a trailing `.` at the end of the non existent file message.
Apart the precision of behaviour change in changes, lgtm!

**Comment by kit-ty-kate** [comment]
ocaml-benchmarks is hitting a 502 bad gateway so i'm guessing it won't start. Ignoring.
