### PR TITLE
Fix lint W59 with a local path that is not an archive

### LINKED ISSUE #6218: Lint W59 warn for missing checksum on local directory source url
When locally path pinning a package, the added url is local and the linting after edit warns that a checksum is missing:
```
[WARNING] The opam file didn't pass validation:
           warning 59: url doesn't contain a checksum
Proceed anyway ('no' will re-edit)? [y/n] y

### PR DESCRIPTION
**Pull request by rjbou**
fix #6218 

backported to 2.3 in https://github.com/ocaml/opam/pull/6220

### CODE REVIEW

File: src/state/opamFileTools.ml [hunk 1]
```diff
@@ -396,9 +396,15 @@ let t_lint ?check_extra_files ?(check_upstream=false) ?(all=false) t =
         | #OpamUrl.version_control -> true
         | _ -> false)
   in
+  let url_archive =
+    let open OpamStd.Option.Op in
+    t.url >>| OpamFile.URL.url >>| (fun u ->
+        OpamSystem.is_archive u.OpamUrl.path)
```
Comment (kit-ty-kate) [inline src/state/opamFileTools.ml:402]: i don't think that's right. `is_archive` will look up the file locally. If you have an url like `https:///etc/fstab`, the path will be looked up.

**Review by kit-ty-kate — CHANGES_REQUESTED** [review]

File: src/state/opamFileTools.ml (hunk 1 above)
Comment (rjbou) [reply src/state/opamFileTools.ml:402]: Good point, we should then add a function that checks if a path looks like an archive, like `looks_like_ssh_path`.

Comment (kit-ty-kate) [reply src/state/opamFileTools.ml:402]: i'm not sure we need a new function. Something like that would work just fine i think:
```suggestion
        OpamSystem.local_file u <> None)
```

Comment (rjbou) [reply src/state/opamFileTools.ml:402]: We don't want to check file existence on disk (which does `OpamUrl.local_file`). We want to know if given string seems like an archive path.

Comment (kit-ty-kate) [reply src/state/opamFileTools.ml:402]: What about using https://github.com/ocaml/opam/pull/5979 instead?

File: tests/reftests/lint.test [hunk 2]
```diff
@@ -884,7 +885,53 @@ license: "ISC"
...
+authors: "the testing team"
+homepage: "egapemoh"
+maintainer: "maint@tain.er"
+license: "ISC"
+dev-repo: "hg+https://to@li.nt"
+bug-reports: "https://nobug"
+### <add-url.sh>
+basedir=$(echo $BASEDIR | sed "s/\\\\\\\\/\\\\\\\\\\\\\\\\/g")
+cat << EOF >> lint.opam
+url { src:"file://$basedir/an-archive" }
```
[the remark this answers is not in the document]
Comment (dra27) [reply tests/reftests/lint.test:908]: Slightly for readability, but I think that you can halve the number of backslashes by using a single-quoted string?

[the remark this answers is not in the document]
Comment (rjbou) [reply tests/reftests/lint.test:908]: Indeed

File: src/core/opamSystem.ml [hunk 3]
```diff
@@ -869,19 +869,23 @@ module Tar = struct
...
+  let get_archive_extension file =
+    List.fold_left
+      (fun acc (ext, t) -> match acc with
+         | Some t -> Some t
+         | None   ->
+           if match_ext file ext
+           then Some t
+           else None)
+      None
+      extensions
```
Comment (kit-ty-kate) [inline src/core/opamSystem.ml:881]: We don’t need to go through the whole list:
```suggestion
    OpamStd.List.find_map_opt (fun (ext, t) ->
        if match_ext file ext then Some t else None)
      extensions
```

File: src/core/opamSystem.mli [hunk 4]
```diff
@@ -233,9 +233,14 @@ val read_command_output: ?verbose:bool -> ?env:string array ->
 
 (** END *)
 
-(** Test whether the file is an archive, by looking as its extension *)
+(** Test whether the file is an archive, by looking at its magic magic number
```
Comment (kit-ty-kate) [inline src/core/opamSystem.mli:236]:
```suggestion
(** Test whether the file is an archive, by looking at its magic number
```

File: tests/reftests/lint.test [hunk 5]
```diff
@@ -884,7 +885,53 @@ license: "ISC"
...
+synopsis: "A word"
+description: "Two words."
+authors: "the testing team"
+homepage: "egapemoh"
+maintainer: "maint@tain.er"
+license: "ISC"
+dev-repo: "hg+https://to@li.nt"
+bug-reports: "https://nobug"
+### <add-url.sh>
+basedir=`echo "$BASEDIR" | sed 's/\\\\/\\\\\\\\\\\\\\\\/g'`
```
Comment (kit-ty-kate) [inline tests/reftests/lint.test:927]: you used single quotes here instead of double-quotes and only halved the left part of the sed, not the right part.
```suggestion
basedir=`echo "$BASEDIR" | sed 's/\\\\/\\\\\\\\/g'`
```

File: tests/reftests/lint.test [hunk 6]
```diff
@@ -884,7 +885,53 @@ license: "ISC"
...
```
Comment (kit-ty-kate) [inline tests/reftests/lint.test:906]: same here
```suggestion
basedir=`echo "$BASEDIR" | sed 's/\\\\/\\\\\\\\/g'`
```

File: tests/reftests/lint.test (hunk 5 above)
Comment (kit-ty-kate) [reply tests/reftests/lint.test:927]: actually what is the goal of this sed? Is it just to escape every backslashes? If so, then the solution might be instead:
```suggestion
basedir=`echo "$BASEDIR" | sed 's/\\/\\\\/g'`
```
I know is everywhere in the reftests in its double-quoted form but i’ve never really understood it ^^"

Comment (rjbou) [reply tests/reftests/lint.test:927]: It's the different levels of escape that are needed to end with `s/\\/\\\\/g` launched.

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks!
