### PR TITLE
opam update: Skip removing a version-equivalent package on rename.

### LINKED ISSUE #6754: Syntaxic differences in version numbers are kept accross updates
Very minor issue and should make very little functional difference (although i might be able to find one, e.g. extract some extra-files or things like that), but it is surprising nonetheless
```
### <pkg:some-pkg.00>
opam-version: "2.0"
### opam install --show some-pkg
[...]
* install some-pkg.00
[...]
### mv REPO/packages/some-pkg/some-pkg.00 REPO/packages/some-pkg/some-pkg.0
### opam update
### opam install --show some-pkg
[...]
* install some-pkg.00
[...]
```
This is a minor regression compared to 2.4 due to https://github.com/ocaml/opam/pull/6614
cc @arozovyk

### PR DESCRIPTION
**Pull request by arozovyk**
Fixes #6754
Backported to 2.5 by https://github.com/ocaml/opam/pull/6784

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you split into 2 commits (one for the test and one for the fix) so that we are able to see the difference?

File: src/state/opamRepositoryState.ml [hunk 1]
```diff
@@ -143,7 +143,9 @@ let load_opams_from_diff repo diffs rt =
     OpamRepositoryName.Map.find repo.repo_name rt.repo_opams
   in
   let repo_root = get_repo_root rt repo in
-  let process_file (opams, processed_dirs) file ~is_removal =
+  (*  processed_dirs: avoid re-read in case of diff generated by extra files.
+      added_pkgs: skip removing version-equivalent packages *)
```
Comment (rjbou) [inline src/state/opamRepositoryState.ml]:
```suggestion
  (*  processed_dirs: used to avoid re-read in case of diff generated by extra files.
      added_pkgs: used to skip removing version-equivalent packages *)
```

File: master_changes.md [hunk 2]
```diff
@@ -125,6 +125,7 @@ users)
 ## opam-repository
 
 ## opam-state
+  * `OpamRepositoryState.load_opams_from_diff` track added packages to avoid removing version-equivalent packages [#6774 @arozovyk fix #6754]
```
Comment (rjbou) [inline master_changes.md:129]: Missing entry in `# Update` for the bug fix

File: tests/reftests/update.test [hunk 3]
```diff
@@ -783,3 +783,124 @@ eta.1: Missing extra-file for
...
+[git-ver] synchronised from git+file://${BASEDIR}/GITREPO
+### opam install pkg-foo.1.0.0~alpha1
+The following actions will be performed:
+=== install 1 package
+  - install pkg-foo 1.0.0~alpha1
+
+<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+-> installed pkg-foo.1.0.0~alpha1
+Done.
+### <GITREPO/packages/lib-foo/lib-foo.1.0.0~alpha1/opam>
```
Comment (rjbou) [inline tests/reftests/update.test:875]:
```suggestion
### :IV:3: Version equivalent rename involved in a conflict
### <GITREPO/packages/lib-foo/lib-foo.1.0.0~alpha1/opam>
```

**Review by rjbou — APPROVED** [review]
