### PR TITLE
Software Heritage fallback fixes

### LINKED ISSUE #5721: opam does not wait for the Software Heritage fallback archives to be "cooked"
When using the software heritage fallback feature, it is understood that regenerating (as noted in #5720) the archive from a given SWHID (called "cooking" by Software Heritage) might take some time. The code currently denotes this by a 60 seconds timer: https://github.com/ocaml/opam/blob/c4961baf23e681c74b381a5f9c2cfd7362740e68/src/repository/opamDownload.ml#L299

However in practice, trying it locally, leads only a short wait then the following failure:
```
OpamSolution.Fetch_fail("\"/opt/homebrew/bin/wget -X POST --content-disposition -t 3 -O - -U opam/2.2.0~alpha2 -- https://archive.softwareheritage.org/api/1/vault/directory/6f61d745641e701d5cad73a9e918d5e888d5ab64/\" exited with code 8 \"2023-11-08 16:00:08 ERROR 404: Not Found.\"")
```
Calling the same command again when the archive has finished cooking, succeeds.

### PR DESCRIPTION
**Pull request by rjbou**
* Fix archive cooking request for `wget`, the wrong option was given
* Fix SWH liveness check, no POST request. It is a hidden bug, it was failing with no error code for curl and as wget had the wrong POST request option it wasn't showing.
* Update SWH API request: [`vault/directory`](https://archive.softwareheritage.org/api/1/vault/directory/doc/) is deprecated in favor to [`vault/flat`](https://archive.softwareheritage.org/api/1/vault/flat/doc/)
* Some doc
fixes #5721

### CODE REVIEW

File: src/repository/opamDownload.ml [hunk 1]
```diff
@@ -246,8 +246,13 @@ module SWHID = struct
   let check_liveness () =
     OpamProcess.Job.catch (fun _ -> Done false)
     @@ fun () ->
-      get_output ~post:true OpamUrl.Op.(instance / "api" / "1" / "ping" / "")
-      @@| fun _ -> true
+    get_output ~post:false OpamUrl.Op.(instance / "api" / "1" / "ping" / "")
+    @@| function
+    | Some (pong::_) ->
+      (* curl output after answer the http code *)
```
Comment (dra27) [inline src/repository/opamDownload.ml:255]: I don't follow the comment - are there situations where curl is doing something different with the output?

File: src/repository/opamDownload.ml [hunk 2]
```diff
@@ -287,7 +290,10 @@ module SWHID = struct
       None
 
   let get_dir hash =
-    let url = full_url "vault/directory" hash in
+    (* https://archive.softwareheritage.org/api/1/vault/flat/doc/ *)
+    let url = vault_url "flat" hash in
+    (* The POST is needed only for asking to cook the archive, it's a no-op on
+       status check *)
```
Comment (dra27) [inline src/repository/opamDownload.ml:296]: I'm not sure what the purpose in the protocol of having `POST` and `GET` as separate verbs (I don't reading the docs see the purpose of the distiction), but could we not have `~post` being an argument for `get_dir` and then alter `get_url` below so that it passes `~post:true` the first time and `~post:false` for any retries (which would be following the protocol, even if it's not clear why the protocol says to do that)?

**Review by dra27 — COMMENTED** [review]
A couple of questions, and I wonder if we may as well strictly follow the protocol for vault/flat, given that the code makes it relatively easy for us to do so.

File: src/repository/opamDownload.ml [hunk 3]
```diff
@@ -224,10 +224,12 @@ let get_output ~post ?(args=[]) url =
   let cmd_args =
     if post then
       match cmd_args with
-      | ("wget"|"curl" as cmd)::args -> Some (cmd :: ["-X"; "POST"] @ args)
+      | ("curl" as cmd)::args -> Some (cmd :: ["--request"; "POST"] @ args)
+      | ("wget" as cmd)::args -> Some (cmd :: ["--post-data"; {|""|}] @ args)
       | _ -> None
     else Some cmd_args
   in
+  OpamConsole.error "%s" (OpamStd.Option.to_string ~none:"XXX" (OpamStd.List.concat_map " " (fun x -> x)) cmd_args);
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/repository/opamDownload.ml:232]: oupsy

File: src/repository/opamDownload.ml [hunk 4]
```diff
@@ -224,10 +224,12 @@ let get_output ~post ?(args=[]) url =
   let cmd_args =
     if post then
       match cmd_args with
-      | ("wget"|"curl" as cmd)::args -> Some (cmd :: ["-X"; "POST"] @ args)
+      | ("curl" as cmd)::args -> Some (cmd :: ["-X"; "POST"] @ args)
+      | ("wget" as cmd)::args -> Some (cmd :: ["--post-data"; {|""|}] @ args)
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/repository/opamDownload.ml:228]: fair enough

File: src/repository/opamDownload.ml (hunk 1 above)
Comment (rjbou) [reply src/repository/opamDownload.ml:255]: curl invocation contains `--write-out "%{http_code}\n"`, so its output on stdout is `"pong"200`

File: src/repository/opamDownload.ml (hunk 2 above)
Comment (rjbou) [reply src/repository/opamDownload.ml:296]: From the protocol
> That endpoint [/vault/flat] enables to create a vault cooking task for a directory through a POST request or check the status of a previously created one through a GET request.

It is possible indeed to have a more robust mechanism:
1. first check with a GET request
  2. It is already cooked -> we get the json directly and go to 5.
  3. It is not cooked -> 404 error (exit 0 on curl and 8 on wget), and we need to retrieve the skipped body (curl -i, wget ?) to analyse the source (cooking not yet requested or object not found)
  4. Request cooking with a POST request
5. Analyse the returned json to retrieve status (and archive url)
6. iterate on 5 until it is cooked

File: src/repository/opamDownload.ml (hunk 1 above)
Comment (dra27) [reply src/repository/opamDownload.ml:254]: Oh, I was being silly - I didn't register that `get_output`'s `cmd_args` of course begins with a call to `download_args` 🤦‍♂️

File: src/repository/opamDownload.ml (hunk 2 above)
Comment (dra27) [reply src/repository/opamDownload.ml:295]: Is this what we're _meant_ to do, though? I don't quite understand why the protocol has bothered with the "dance" - if what we're presently doing of just always POSTing is OK, what's the purpose of having the behaviour of GET being different?

Comment (dra27) [reply src/repository/opamDownload.ml:295]: This doesn't have to block merging, though, if we're sure that POSTing each time definitely isn't an issue.

**Review by dra27 — APPROVED** [review]
LGTM - I'm puzzled by the slightly arcane way swh seems to specify vault/flat, but that doesn't need to affect the code here!

**Review by kit-ty-kate — APPROVED** [review]

**Comment by rjbou** [comment]
Updated!
Some outputs:
<details>
<summary> <b>wget & not cooked</b></summary>

```shell
> ./opam install  -vvv --debug -y swh-wget-not-cooked
[...]

[...]
The following actions will be performed:
=== install 1 package
  ∗ swh-wget-not-cooked 1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/3: [swh-wget-not-cooked.1: http]
+ /usr/bin/wget "-t" "3" "-O" "/tmp/opam-1102792-e86235/fkdjhfskjfhsjkdhfake.o.r.g.part" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://fkdjhfskjfhsjkdhfake.o.r.g/"
- --2024-11-15 16:08:51--  https://fkdjhfskjfhsjkdhfake.o.r.g/
- Resolving fkdjhfskjfhsjkdhfake.o.r.g (fkdjhfskjfhsjkdhfake.o.r.g)... failed: Name or service not known.
- wget: unable to resolve host address ‘fkdjhfskjfhsjkdhfake.o.r.g’
+ /usr/bin/wget "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/ping/"
- --2024-11-15 16:08:51--  https://archive.softwareheritage.org/api/1/ping/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:08:51 GMT
-   Content-Type: application/json
-   Content-Length: 6
-   Vary: Accept, origin, Cookie
-   Allow: HEAD, GET, OPTIONS, OPTIONS
-   X-RateLimit-Limit: 120
-   X-RateLimit-Remaining: 113
-   X-RateLimit-Reset: 1731685708
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 47910447
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 6 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100% 8.32M=0s
- 
- 2024-11-15 16:08:51 (8.32 MB/s) - written to stdout [6/6]
- 
- "pong"
00:14.316  CURL(SWHID)            API is working
Source https://fkdjhfskjfhsjkdhfake.o.r.g/ is not available. Do you want to try to retrieve it from Software Heritage cache
(https://www.softwareheritage.org)? It may take few minutes. [y/n] y
00:14.317  CURL(SWHID)            SWH fallback for swh-wget-not-cooked.1 with swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331
Processing  1/3:
+ /usr/bin/wget "--content-on-error" "-t" "3" "-O" "/opamroot/log/swh-out-1102792-c8bbc0" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/"
- --2024-11-15 16:08:51--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 404 Not Found
-   Date: Fri, 15 Nov 2024 15:08:51 GMT
-   Content-Type: application/json
-   Content-Length: 121
-   Expires: Fri, 15 Nov 2024 15:08:51 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: POST, OPTIONS, GET
-   X-RateLimit-Limit: 60
-   X-RateLimit-Remaining: 59
-   X-RateLimit-Reset: 1731683391
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 50336527
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Connection: keep-alive
- Saving to: ‘/opamroot/log/swh-out-1102792-c8bbc0’
- 
-      0K                                                       100%  224M=0s
- 
- 2024-11-15 16:08:51 ERROR 404: Not Found.
- 
00:14.528  CURL(SWHID)            swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331 is uncooked, request cooking
+ /usr/bin/wget "--method" "POST" "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/"
- --2024-11-15 16:08:51--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:08:52 GMT
-   Content-Type: application/json
-   Content-Length: 240
-   Expires: Fri, 15 Nov 2024 15:08:52 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: POST, OPTIONS, GET
-   X-RateLimit-Limit: 120
-   X-RateLimit-Remaining: 119
-   X-RateLimit-Reset: 1731686931
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 53773176
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 240 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100%  938M=0s
- 
- 2024-11-15 16:08:52 (938 MB/s) - written to stdout [240/240]
- 
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/","progress_message":null,"id":416944911,"status":"new","swhid":"swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331"}
00:14.867  CURL(SWHID)            swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331 is cooking...
+ /usr/bin/wget "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/"
- --2024-11-15 16:09:02--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:09:02 GMT
-   Content-Type: application/json
-   Content-Length: 240
-   Expires: Fri, 15 Nov 2024 15:09:02 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: POST, OPTIONS, GET
-   X-RateLimit-Limit: 60
-   X-RateLimit-Remaining: 58
-   X-RateLimit-Reset: 1731683391
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 45750401
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 240 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100%  288M=0s
- 
- 2024-11-15 16:09:02 (288 MB/s) - written to stdout [240/240]
- 
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/","progress_message":null,"id":416944911,"status":"new","swhid":"swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331"}
00:25.063  CURL(SWHID)            swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331 is cooking...
+ /usr/bin/wget "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/"
- --2024-11-15 16:09:12--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:09:12 GMT
-   Content-Type: application/json
-   Content-Length: 240
-   Expires: Fri, 15 Nov 2024 15:09:12 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: GET, POST, OPTIONS
-   X-RateLimit-Limit: 60
-   X-RateLimit-Remaining: 57
-   X-RateLimit-Reset: 1731683391
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 53283606
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 240 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100%  300M=0s
- 
- 2024-11-15 16:09:12 (300 MB/s) - written to stdout [240/240]
- 
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/","progress_message":null,"id":416944911,"status":"new","swhid":"swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331"}
00:35.263  CURL(SWHID)            swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331 is cooking...
+ /usr/bin/wget "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/"
- --2024-11-15 16:09:22--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:09:22 GMT
-   Content-Type: application/json
-   Content-Length: 240
-   Expires: Fri, 15 Nov 2024 15:09:22 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: GET, POST, OPTIONS
-   X-RateLimit-Limit: 60
-   X-RateLimit-Remaining: 56
-   X-RateLimit-Reset: 1731683391
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 55281750
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 240 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100%  245M=0s
- 
- 2024-11-15 16:09:22 (245 MB/s) - written to stdout [240/240]
- 
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/","progress_message":null,"id":416944911,"status":"new","swhid":"swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331"}
00:45.481  CURL(SWHID)            swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331 is cooking...
+ /usr/bin/wget "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/"
- --2024-11-15 16:09:32--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:09:32 GMT
-   Content-Type: application/json
-   Content-Length: 240
-   Expires: Fri, 15 Nov 2024 15:09:32 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: OPTIONS, POST, GET
-   X-RateLimit-Limit: 60
-   X-RateLimit-Remaining: 55
-   X-RateLimit-Reset: 1731683391
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 52529512
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 240 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100%  272M=0s
- 
- 2024-11-15 16:09:33 (272 MB/s) - written to stdout [240/240]
- 
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/","progress_message":null,"id":416944911,"status":"new","swhid":"swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331"}
00:55.864  CURL(SWHID)            swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331 is cooking...
+ /usr/bin/wget "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/"
- --2024-11-15 16:09:43--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:09:43 GMT
-   Content-Type: application/json
-   Content-Length: 241
-   Expires: Fri, 15 Nov 2024 15:09:43 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: GET, OPTIONS, POST
-   X-RateLimit-Limit: 60
-   X-RateLimit-Remaining: 54
-   X-RateLimit-Reset: 1731683391
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 39989269
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 241 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100% 1.18G=0s
- 
- 2024-11-15 16:09:43 (1.18 GB/s) - written to stdout [241/241]
- 
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/","progress_message":null,"id":416944911,"status":"done","swhid":"swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331"}
01:06.211  CURL(SWHID)            Downloading swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331 for swh-wget-not-cooked.1
+ /usr/bin/wget "-t" "3" "-O" "/tmp/opam-1102792-70a205/6394e653c9dfa1be07250529c461dcd7983cd331.part" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/"
- --2024-11-15 16:09:43--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6394e653c9dfa1be07250529c461dcd7983cd331/raw/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 302 Found
-   Date: Fri, 15 Nov 2024 15:09:43 GMT
-   Content-Type: text/html; charset=utf-8
-   Content-Length: 0
-   Location: https://swhvaultstorage.blob.core.windows.net/contents-uncompressed/f2391ef00cb8cab822ba66e4f9bdb0f782b84bfd?se=2024-11-16T15%3A09%3A43Z&sp=r&sv=2024-11-04&sr=b&rscd=attachment%3B%20filename%3D%22swh_1_dir_6394e653c9dfa1be07250529c461dcd7983cd331.tar.gz%22&sig=3N2KiPjDIRFVfpGo6PLwr8syJab5Ye7Q8jKJW66G0oM%3D
-   Vary: Accept, origin, Cookie
-   Allow: OPTIONS, GET, OPTIONS, HEAD
-   X-RateLimit-Limit: 120
-   X-RateLimit-Remaining: 112
-   X-RateLimit-Reset: 1731685708
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 52431141
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Connection: keep-alive
- Location: https://swhvaultstorage.blob.core.windows.net/contents-uncompressed/f2391ef00cb8cab822ba66e4f9bdb0f782b84bfd?se=2024-11-16T15%3A09%3A43Z&sp=r&sv=2024-11-04&sr=b&rscd=attachment%3B%20filename%3D%22swh_1_dir_6394e653c9dfa1be07250529c461dcd7983cd331.tar.gz%22&sig=3N2KiPjDIRFVfpGo6PLwr8syJab5Ye7Q8jKJW66G0oM%3D [following]
- --2024-11-15 16:09:43--  https://swhvaultstorage.blob.core.windows.net/contents-uncompressed/f2391ef00cb8cab822ba66e4f9bdb0f782b84bfd?se=2024-11-16T15%3A09%3A43Z&sp=r&sv=2024-11-04&sr=b&rscd=attachment%3B%20filename%3D%22swh_1_dir_6394e653c9dfa1be07250529c461dcd7983cd331.tar.gz%22&sig=3N2KiPjDIRFVfpGo6PLwr8syJab5Ye7Q8jKJW66G0oM%3D
- Resolving swhvaultstorage.blob.core.windows.net (swhvaultstorage.blob.core.windows.net)... 20.209.11.33
- Connecting to swhvaultstorage.blob.core.windows.net (swhvaultstorage.blob.core.windows.net)|20.209.11.33|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Content-Length: 15559
-   Content-Type: application/octet-stream
-   Content-MD5: 7HYlM4kpCKEi2SPr0xMKyA==
-   Last-Modified: Fri, 15 Nov 2024 15:09:38 GMT
-   Accept-Ranges: bytes
-   ETag: "0x8DD058785ED331E"
-   Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
-   x-ms-request-id: d6c83cff-a01e-0017-3b70-3757dc000000
-   x-ms-version: 2024-11-04
-   x-ms-creation-time: Fri, 15 Nov 2024 15:09:38 GMT
-   x-ms-lease-status: unlocked
-   x-ms-lease-state: available
-   x-ms-blob-type: BlockBlob
-   Content-Disposition: attachment; filename="swh_1_dir_6394e653c9dfa1be07250529c461dcd7983cd331.tar.gz"
-   x-ms-server-encrypted: true
-   Access-Control-Allow-Origin: *
-   Date: Fri, 15 Nov 2024 15:09:43 GMT
- Length: 15559 (15K) [application/octet-stream]
- Saving to: ‘/tmp/opam-1102792-70a205/6394e653c9dfa1be07250529c461dcd7983cd331.part’
- 
-      0K .......... .....                                      100% 1.31G=0s
- 
- 2024-11-15 16:09:44 (1.31 GB/s) - ‘/tmp/opam-1102792-70a205/6394e653c9dfa1be07250529c461dcd7983cd331.part’ saved [15559/15559]
- 
+ /usr/bin/tar "xfz" "/tmp/opam-1102792-70a205/6394e653c9dfa1be07250529c461dcd7983cd331" "-C" "/tmp/opam-1102792-b35983"
⬇ retrieved swh-wget-not-cooked.1  (SWH fallback)
[...]
```
</details>

<details>
<summary> <b>cURL & not cooked</b></summary>

```shell
> ./opam install  -vvv --debug -y swh-curl-not-cooked
[...]
The following actions will be performed:
=== install 1 package
  ∗ swh-curl-not-cooked 1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/3: [swh-curl-not-cooked.1: http]
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "/tmp/opam-360556-43cf30/i-am-not-available-fake.o.r.g.part" "--" "https://i-am-not-available-fake.o.r.g/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
- Warning: Problem : timeout. Will retry in 2 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
- Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
- Warning: Problem : timeout. Will retry in 2 seconds. 1 retries left.
- 000
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "-" "--" "https://archive.softwareheritage.org/api/1/ping/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100     6  100     6    0     0     49      0 --:--:-- --:--:-- --:--:--    50
- "pong"200
00:17.873  CURL(SWHID)            API is working
Source https://i-am-not-available-fake.o.r.g/ is not available. Do you want to try to retrieve it from
Software Heritage cache (https://www.softwareheritage.org)? It may take few minutes. [y/n] y
00:17.873  CURL(SWHID)            SWH fallback for swh-curl-not-cooked.1 with swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b
Processing  1/3:
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "/opamroot/log/swh-out-360556-b9353e" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/"
- 404
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100   121  100   121    0     0    741      0 --:--:-- --:--:-- --:--:--   746
00:18.065  CURL(SWHID)            swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b is uncooked, request cooking
+ /usr/bin/curl "--request" "POST" "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "-" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100   240  100   240    0     0    863      0 --:--:-- --:--:-- --:--:--   866
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/raw/","progress_message":null,"id":416941408,"status":"new","swhid":"swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b"}200
00:18.371  CURL(SWHID)            swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b is cooking...
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "-" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100   255  100   255    0     0   1735      0 --:--:-- --:--:-- --:--:--  1734
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/raw/","progress_message":"Processing...","id":416941408,"status":"pending","swhid":"swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b"}200
00:28.550  CURL(SWHID)            swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b is cooking...
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "-" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100   255  100   255    0     0   1850      0 --:--:-- --:--:-- --:--:--  1861
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/raw/","progress_message":"Processing...","id":416941408,"status":"pending","swhid":"swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b"}200
00:38.718  CURL(SWHID)            swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b is cooking...
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "-" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100   241  100   241    0     0   1726      0 --:--:-- --:--:-- --:--:--  1733
- {"fetch_url":"https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/raw/","progress_message":null,"id":416941408,"status":"done","swhid":"swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b"}200
00:48.886  CURL(SWHID)            Downloading swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b for swh-curl-not-cooked.1
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "/tmp/opam-360556-ffbc05/7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b.part" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b/raw/"
- 200
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12495  100 12495    0     0  29676      0 --:--:-- --:--:-- --:--:-- 29676
+ /usr/bin/tar "xfz" "/tmp/opam-360556-ffbc05/7a79aa8ded5a648e6a3ed19ee3a64e1a32c8672b" "-C" "/tmp/opam-360556-0a2c9e"
⬇ retrieved swh-curl-not-cooked.1  (SWH fallback)
[...]
```
</details>

<details>
<summary> <b>wget & cooked</b></summary>

```shell
> ./opam install  -vvv --debug -y swh-wget-cooked
[...]
The following actions will be performed:
=== install 1 package
  ∗ swh-wget-cooked 1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/3: [swh-wget-cooked.1: http]
+ /usr/bin/wget "-t" "3" "-O" "/tmp/opam-1100962-6df63b/fkdjhfskjfhsjkdhfake.o.r.g.part" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://fkdjhfskjfhsjkdhfake.o.r.g/"
- --2024-11-15 16:05:51--  https://fkdjhfskjfhsjkdhfake.o.r.g/
- Resolving fkdjhfskjfhsjkdhfake.o.r.g (fkdjhfskjfhsjkdhfake.o.r.g)... failed: Name or service not known.
- wget: unable to resolve host address ‘fkdjhfskjfhsjkdhfake.o.r.g’
+ /usr/bin/wget "-t" "3" "-O" "-" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/ping/"
- --2024-11-15 16:05:51--  https://archive.softwareheritage.org/api/1/ping/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:05:51 GMT
-   Content-Type: application/json
-   Content-Length: 6
-   Vary: Accept, origin, Cookie
-   Allow: OPTIONS, GET, OPTIONS, HEAD
-   X-RateLimit-Limit: 120
-   X-RateLimit-Remaining: 115
-   X-RateLimit-Reset: 1731685708
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 54232414
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 6 [application/json]
- Saving to: ‘STDOUT’
- 
-      0K                                                       100% 22.9M=0s
- 
- 2024-11-15 16:05:51 (22.9 MB/s) - written to stdout [6/6]
- 
- "pong"
00:13.858  CURL(SWHID)            API is working
Source https://fkdjhfskjfhsjkdhfake.o.r.g/ is not available. Do you want to try to retrieve it from
Software Heritage cache (https://www.softwareheritage.org)? It may take few minutes. [y/n] y
00:13.858  CURL(SWHID)            SWH fallback for swh-wget-cooked.1 with swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4
Processing  1/3:
+ /usr/bin/wget "--content-on-error" "-t" "3" "-O" "/opamroot/log/swh-out-1100962-7f8485" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4/"
- --2024-11-15 16:05:51--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Date: Fri, 15 Nov 2024 15:05:51 GMT
-   Content-Type: application/json
-   Content-Length: 241
-   Expires: Fri, 15 Nov 2024 15:05:51 GMT
-   Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
-   Vary: Accept, origin, Cookie
-   Allow: POST, OPTIONS, GET
-   X-RateLimit-Limit: 60
-   X-RateLimit-Remaining: 59
-   X-RateLimit-Reset: 1731683211
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 47910295
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Accept-Ranges: bytes
-   Connection: keep-alive
- Length: 241 [application/json]
- Saving to: ‘/opamroot/log/swh-out-1100962-7f8485’
- 
-      0K                                                       100%  143M=0s
- 
- 2024-11-15 16:05:51 (143 MB/s) - ‘/opamroot/log/swh-out-1100962-7f8485’ saved [241/241]
- 
00:14.101  CURL(SWHID)            swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4 is cooked, requesting url
00:14.101  CURL(SWHID)            Downloading swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4 for swh-wget-cooked.1
+ /usr/bin/wget "-t" "3" "-O" "/tmp/opam-1100962-3d90aa/6b700f4b287aee509adbc723d0303098188604f4.part" "--server-response" "-U" "opam/2.4.0~alpha1~dev" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4/raw/"
- --2024-11-15 16:05:51--  https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4/raw/
- Resolving archive.softwareheritage.org (archive.softwareheritage.org)... 128.93.166.15
- Connecting to archive.softwareheritage.org (archive.softwareheritage.org)|128.93.166.15|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 302 Found
-   Date: Fri, 15 Nov 2024 15:05:52 GMT
-   Content-Type: text/html; charset=utf-8
-   Content-Length: 0
-   Location: https://swhvaultstorage.blob.core.windows.net/contents-uncompressed/94f715535502200f7a4ede59a85d22dda9fc3510?se=2024-11-16T15%3A05%3A52Z&sp=r&sv=2024-11-04&sr=b&rscd=attachment%3B%20filename%3D%22swh_1_dir_6b700f4b287aee509adbc723d0303098188604f4.tar.gz%22&sig=9DEL7O0yEMhxz3Wgvo3QgJ6180mkDIjuV4rKoBCTRTc%3D
-   Vary: Accept, origin, Cookie
-   Allow: OPTIONS, OPTIONS, GET, HEAD
-   X-RateLimit-Limit: 120
-   X-RateLimit-Remaining: 114
-   X-RateLimit-Reset: 1731685708
-   X-Frame-Options: DENY
-   X-Content-Type-Options: nosniff
-   Referrer-Policy: same-origin
-   Cross-Origin-Opener-Policy: same-origin
-   X-Varnish: 52136120
-   Age: 0
-   Via: 1.1 varnish (Varnish/6.5)
-   Strict-Transport-Security: max-age=15768000;
-   Connection: keep-alive
- Location: https://swhvaultstorage.blob.core.windows.net/contents-uncompressed/94f715535502200f7a4ede59a85d22dda9fc3510?se=2024-11-16T15%3A05%3A52Z&sp=r&sv=2024-11-04&sr=b&rscd=attachment%3B%20filename%3D%22swh_1_dir_6b700f4b287aee509adbc723d0303098188604f4.tar.gz%22&sig=9DEL7O0yEMhxz3Wgvo3QgJ6180mkDIjuV4rKoBCTRTc%3D [following]
- --2024-11-15 16:05:52--  https://swhvaultstorage.blob.core.windows.net/contents-uncompressed/94f715535502200f7a4ede59a85d22dda9fc3510?se=2024-11-16T15%3A05%3A52Z&sp=r&sv=2024-11-04&sr=b&rscd=attachment%3B%20filename%3D%22swh_1_dir_6b700f4b287aee509adbc723d0303098188604f4.tar.gz%22&sig=9DEL7O0yEMhxz3Wgvo3QgJ6180mkDIjuV4rKoBCTRTc%3D
- Resolving swhvaultstorage.blob.core.windows.net (swhvaultstorage.blob.core.windows.net)... 20.209.11.33
- Connecting to swhvaultstorage.blob.core.windows.net (swhvaultstorage.blob.core.windows.net)|20.209.11.33|:443... connected.
- HTTP request sent, awaiting response... 
-   HTTP/1.1 200 OK
-   Content-Length: 4213
-   Content-Type: application/octet-stream
-   Content-MD5: +jpEuytdGqLxCrKdtXLUMg==
-   Last-Modified: Wed, 19 Jun 2024 21:00:34 GMT
-   Accept-Ranges: bytes
-   ETag: "0x8DC90A2DD052E92"
-   Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
-   x-ms-request-id: 041ed48b-601e-0027-456f-37e913000000
-   x-ms-version: 2024-11-04
-   x-ms-creation-time: Wed, 19 Jun 2024 21:00:34 GMT
-   x-ms-lease-status: unlocked
-   x-ms-lease-state: available
-   x-ms-blob-type: BlockBlob
-   Content-Disposition: attachment; filename="swh_1_dir_6b700f4b287aee509adbc723d0303098188604f4.tar.gz"
-   x-ms-server-encrypted: true
-   Access-Control-Allow-Origin: *
-   Date: Fri, 15 Nov 2024 15:05:52 GMT
- Length: 4213 (4.1K) [application/octet-stream]
- Saving to: ‘/tmp/opam-1100962-3d90aa/6b700f4b287aee509adbc723d0303098188604f4.part’
- 
-      0K ....                                                  100%  268M=0s
- 
- 2024-11-15 16:05:52 (268 MB/s) - ‘/tmp/opam-1100962-3d90aa/6b700f4b287aee509adbc723d0303098188604f4.part’ saved [4213/4213]
- 
+ /usr/bin/tar "xfz" "/tmp/opam-1100962-3d90aa/6b700f4b287aee509adbc723d0303098188604f4" "-C" "/tmp/opam-1100962-c8b6c4"
⬇ retrieved swh-wget-cooked.1  (SWH fallback)
[...]
```
</details>

<details>
<summary> <b>cURL & cooked</b></summary>

```shell
> ./opam install  -vvv --debug -y swh-curl-cooked
[...]
The following actions will be performed:
=== install 1 package
  ∗ swh-curl-cooked 1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/3: [swh-curl-cooked.1: http]
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "/tmp/opam-1090321-caeea4/i-am-not-available-fake.o.r.g.part" "--" "https://i-am-not-available-fake.o.r.g/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
- Warning: Problem : timeout. Will retry in 2 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
- Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
- Warning: Problem : timeout. Will retry in 2 seconds. 1 retries left.
- 000
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: i-am-not-available-fake.o.r.g
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "-" "--" "https://archive.softwareheritage.org/api/1/ping/"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100     6  100     6    0     0     10      0 --:--:-- --:--:-- --:--:--    10
- "pong"200
00:21.231  CURL(SWHID)            API is working
Source https://i-am-not-available-fake.o.r.g/ is not available. Do you want to try to retrieve it from
Software Heritage cache (https://www.softwareheritage.org)? It may take few minutes. [y/n] y
00:21.231  CURL(SWHID)            SWH fallback for swh-curl-cooked.1 with swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4
Processing  1/3:
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "/opamroot/log/swh-out-1090321-b8392a" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4/"
- 200
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
100   241  100   241    0     0   1173      0 --:--:-- --:--:-- --:--:--  1169
00:21.955  CURL(SWHID)            swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4 is cooked, requesting url
00:21.956  CURL(SWHID)            Downloading swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4 for swh-curl-cooked.1
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.4.0~alpha1~dev" "-L" "-o" "/tmp/opam-1090321-fb6640/6b700f4b287aee509adbc723d0303098188604f4.part" "--" "https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:6b700f4b287aee509adbc723d0303098188604f4/raw/"
- 200
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4213  100  4213    0     0   7233      0 --:--:-- --:--:-- --:--:--  7233
+ /usr/bin/tar "xfz" "/tmp/opam-1090321-fb6640/6b700f4b287aee509adbc723d0303098188604f4" "-C" "/tmp/opam-1090321-5ea6ea"
⬇ retrieved swh-curl-cooked.1  (SWH fallback)
[...]
```
</details>

Some logging enhancement were done after the output: counting of tries, and change `swhid is cooked` to `swhid is cooked or cooking` as it may be currently cooking.

File: src/repository/opamDownload.ml (hunk 2 above)
Comment (rjbou) [reply src/repository/opamDownload.ml]: Update to remove all-PÖST requests

**Review by kit-ty-kate — COMMENTED** [review]
is the `download: parse http error code for wget too and permit to retrieve it.` commit absolutely necessary for this fix or can it be moved to a separate PR and be discussed separately? If this is possible i would rather review this change separately (with `repository: add re as a dependency of opam-repository` as both are related) so that this fix gets merged quicker (e.g. i personally don't think it's a good idea to parse `--server-response`)

File: src/repository/opamDownload.ml [hunk 5]
```diff
@@ -37,6 +37,7 @@ let curl_args =
       (* --fail is as old as curl; though the assumption that it leads to exit
          code 22 when there's an error is probably 5.3 21-Dec-1998 (prior to
          that it led to exit code 21) *)
+      (CString "--show-headers", None) ::
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/repository/opamDownload.ml:40]: Hmm... maybe i should look for another option if this is not available everywhere
```
       -i, --show-headers
              (HTTP FTP) Show response headers in the output. HTTP response headers can include things like server name, cookies, date of the document, HTTP version and more. With
              non-HTTP protocols, the "headers" are other server communication.

File: src/repository/opamDownload.ml [hunk 6]
```diff
@@ -261,7 +261,7 @@ let get_output ~post ?(args=[]) url =
   let cmd_args =
     if post then
       match cmd_args with
-      | ("curl" as cmd)::args -> Some (cmd :: ["-X"; "POST"] @ args)
+      | ("curl" as cmd)::args -> Some (cmd :: ["--request"; "POST"] @ args)
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/repository/opamDownload.ml:321]: It's a personal view: i think it's better to use long form of options, it's easier to understand.

**Comment by rjbou** [comment]
> is the `download: parse http error code for wget too and permit to retrieve it.` commit absolutely necessary for this fix or can it be moved to a separate PR and be discussed separately? If this is possible i would rather review this change separately (with `repository: add re as a dependency of opam-repository` as both are related) so that this fix gets merged quicker (e.g. i personally don't think it's a good idea to parse `--server-response`)

To check if the archive is cooked, we need to do a first request that answers a 404 if it is not cooked, with a json as body containing a specific error. With that, it is possible to request a cooking as a second step. So to have the good workflow (and not handle all 400+ errors as uncooked), it is better to have the fine grained error code retrieval.

Discussed in dev meeting: the way it is done is not the best (parse plain text headers), but with wget there is no way to do it in another way. So we conclude that for the moment we'll propose the SWH fallback only with curl to avoid that brittle parsing. It'll be ported to another PR, like that if one day we want to have wget support, we have the code almost ready.

File: master_changes.md [hunk 7]
```diff
@@ -62,6 +62,11 @@ users)
 
 ## Repository
   * Accurately tag `curl` download command when loaded from global config file [#6270 @rjbou]
+  * Remove wget support for Software Heritage fallback [#6036 @rjbou]
+  * [BUG] Fix SWH archive cooking request for wget [#6036 @rjbou - fix #5721]
```
Comment (rjbou) [inline master_changes.md:66]:
```suggestion
```

**Review by kit-ty-kate — COMMENTED** [review]
full review is still positive, i have a bit more suggestions though

File: src/core/opamFilename.ml [hunk 8]
```diff
@@ -266,6 +266,12 @@ let exists filename =
 let opt_file filename =
   if exists filename then Some filename else None
 
+let with_tmp_file fn =
```
Comment (rjbou) [inline src/core/opamFilename.ml:269]: Should it be `tmp` as `with_tmp_dir` of `temp` as `temp_file`...

File: src/repository/opamDownload.ml [hunk 9]
```diff
@@ -283,13 +286,24 @@ module SWHID = struct
...
-      get_output ~post:true OpamUrl.Op.(instance / "api" / "1" / "ping" / "")
-      @@| fun _ -> true
+  let fallback_err fmt = Printf.sprintf ("SWH fallback: "^^fmt)
+
+  let get_output ?(post=false) url =
+    get_output ~post url @@| function
+    | Some out -> out
+    | None ->
+      (* Shouldn't happen, we already checked that a post tool is used *)
+      (* XXX change to an assert false ? *)
```
Comment (rjbou) [inline src/repository/opamDownload.ml:301]: I don't think this display is needed, as in this module the main entry `archive_fallback` checks that.

File: src/repository/opamDownload.ml [hunk 10]
```diff
@@ -313,120 +408,134 @@ module SWHID = struct
...
                   (Some (fallback_err "unreachable"),
                    fallback_err "network failure or API down"))
-      else
+      | _ ->
         Done (Not_available
                 (Some (fallback_err "no retrieval"),
-                 fallback_err "Download tool permitting post request (%s) not \
-                 set as download tool"
-                   (OpamStd.Format.pretty_list post_tools)))
+                 fallback_err "Curl is required for Software Heritage fallback"))
```
Comment (rjbou) [inline src/repository/opamDownload.ml:540]:
```suggestion
                 fallback_err "curl is required for Software Heritage fallback"))
```

File: src/repository/opamDownload.ml [hunk 11]
```diff
@@ -263,6 +263,7 @@ let download ?quiet ?validate ~overwrite ?compress ?checksum url dstdir =
 
 let get_output ~post ?(args=[]) url =
   let cmd_args =
+    (* should we read from output or redirect in a file ? *)
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/repository/opamDownload.ml:265]:
```suggestion
```

File: .gitignore [hunk 12]
```diff
@@ -99,3 +99,4 @@ doc/*.build
 src/x_build_libs.ocp
 # dev setup
 /.ocamlinit
+release/out
```
Comment (kit-ty-kate) [inline .gitignore:102]:
```suggestion
/release/out
```
otherwise it matches all directories `out` with a parent directory `release`

File: src/repository/opamDownload.ml [hunk 13]
```diff
@@ -253,12 +253,6 @@ let download ?quiet ?validate ~overwrite ?compress ?checksum url dstdir =
 
 (** Stdout output retrieval and post requests management *)
 
-let post_tools = ["wget"; "curl"]
-let check_post_tool () =
```
[the remark this answers is not in the document]
Comment (kit-ty-kate) [reply src/repository/opamDownload.ml:257]: i think removing it is cleaner

File: src/core/opamFilename.ml (hunk 8 above)
Comment (kit-ty-kate) [reply src/core/opamFilename.ml:269]: `tmp` is better imo because it follows the convention from the other similar functions from the same module. aka. `temp` only for the base function (`mk_temp_dir` and `temp_file`) then `tmp` for derived functions (`with_tmp_dir`, `in_tmp_dir` and `with_tmp_dir_job`)

File: src/repository/opamDownload.ml (hunk 9 above)
Comment (kit-ty-kate) [reply src/repository/opamDownload.ml:305]: in that case i agree this could be replaced by `assert false`

File: tests/reftests/swhid.unix.test [hunk 14]
```diff
@@ -152,7 +136,7 @@ The following actions will be performed:
 <><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
 [ERROR] Failed to get sources of snappy-swhid-ko.2: SWH fallback: no retrieval
 
-OpamSolution.Fetch_fail("SWH fallback: Download tool permitting post request (wget and curl) not set as download tool")
+OpamSolution.Fetch_fail("SWH fallback: Curl is required for Software Heritage fallback")
```
Comment (rjbou) [inline tests/reftests/swhid.unix.test:139]:
```suggestion
OpamSolution.Fetch_fail("SWH fallback: curl is required for Software Heritage fallback")
```

File: master_changes.md [hunk 15]
```diff
@@ -161,6 +165,9 @@ users)
   * `OpamArg.InvalidCLI`: export exception [#6150 @rjbou]
 
 ## opam-repository
+  * `OpamDownload.get_output`: fix `wget` option for `POST` requests [#6036 @rjbou]
+  * `OpamDownload.get_output`: use long form for `curl` `POST` request option [#6036 @rjbou]
+  * `OpamDownload.download`: more fine grained HTTP request error code detection for curl [#6036 @rjbou]
```
Comment (rjbou) [inline master_changes.md:170]:
```suggestion
  * `OpamDownload.download`: more fine grained HTTP request error code detection for curl [#6036 @rjbou]
  * `OpamDownload`: remove internal `check_post_tool` and `post_tools` as it was only used to check tools for Software availaibility fallback. With wget support removal, it is no more needed. [#6036]
```

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks!
