### PR TITLE
Consistent accepted repository links 

### LINKED ISSUE #4673: doesn't work: custom repo when creating switch
In the [manual](https://opam.ocaml.org/doc/man/opam-switch.html):

> Prepare a local switch for building the packages defined in ./. This scans the current directory for package definitions, chooses a compatible compiler, creates a local switch and installs the local package dependencies.
> ```
> opam switch create trunk --repos default,beta=https://github.com/ocaml/ocaml-beta-repository.git ocaml-variants.4.10.0+trunk
> ```

This command fails with:

```
Creating repository beta...
[ERROR] Could not update repository "beta": OpamDownload.Download_fail(_, "curl: code 404 while
        downloading https://github.com/ocaml/ocaml-beta-repository.git/index.tar.gz")
[ERROR] Initial fetch of these repositories failed: beta
```

I also tried with my own custom repo and it fails with the same error.

(opam version 2.0.8)

### PR DESCRIPTION
**Pull request by Keryan-dev**
`opam switch create foo --repos bar=[url]` should no longer require `git+` to be accepted. Consistent with `opam repository add`.

fixes #4673

### CODE REVIEW

**Review by kit-ty-kate — APPROVED** [review]

File: src/client/opamCommands.ml [hunk 1]
```diff
@@ -2565,7 +2565,7 @@ let with_repos_rt gt repos f =
           | (n, Some url) ->
             let repo =
               OpamStd.Option.Op.(
-                OpamUrl.parse_opt ~handle_suffix:false ~from_file:false url
+                OpamUrl.parse_opt ~from_file:false url
```
Comment (dra27) [inline src/client/opamCommands.ml:2568]: cf. https://github.com/ocaml/opam/issues/4673#issuecomment-872888360 - this ought to be CLI-version guarded, but that shouldn’t be too bad, as the version check _is_ then the value passed as `handle_suffix`

File: src/client/opamCommands.ml [hunk 2]
```diff
@@ -2563,9 +2563,10 @@ let with_repos_rt gt repos f =
       OpamStd.List.filter_map (function
           | (_, None) -> None
           | (n, Some url) ->
+            let handle_suffix = OpamCLIVersion.(current >= (2,2)) in
```
[the remark this answers is not in the document]
Comment (Keryan-dev) [reply src/client/opamCommands.ml:2566]: This isn't right anyway so I'll repatch it. 
But `OpamCLIVersion` redefined comparison so I reckon I should make sure to use that.

File: tests/reftests/switch-creation.test [hunk 3]
```diff
@@ -49,7 +49,7 @@ Done.
 ${BASEDIR}/OPAM/undef-switch
 ### # switch with repo link
 ### # expects a warning, useful to check chosen backend
-### opam switch create w-repo --repositories=from-link=git+https://github.com/ocaml/opam-repository.git --dry-run --empty
+### opam switch create w-repo --repositories=from-link=https://github.com/ocaml/opam-repository.git --dry-run --empty
```
Comment (kit-ty-kate) [inline tests/reftests/switch-creation.test:52]: The reason we split tests and changes in separate commits is to the what has changed easier.
I think it would be better to not change the tests and show the command fail in the previous commit, then in this one you'd be able to see what the actual change is.

File: src/client/opamCommands.ml [hunk 4]
```diff
@@ -2710,7 +2711,7 @@ let switch cli =
           compatible compiler, creates a local switch and installs the local \
           package dependencies.";
       `Pre "    opam switch create trunk --repos \
-            default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git \
+            default,beta=https://github.com/ocaml/ocaml-beta-repository.git \
             ocaml-variants.4.10.0+trunk";
```
Comment (rjbou) [inline src/client/opamCommands.ml:2715]: This should also be guarder by a cli version, no ?
```ocaml
      `Pre (Printf.sprintf
              "    opam switch create trunk --repos \
               default,beta=https://github.com/ocaml/ocaml-beta-repository.git \
               ocaml-variants.4.10.0+trunk"
              (if OpamCLIVersion.Op.(cli @>= cli2_3) then "" else "git+"));

**Review by rjbou — APPROVED** [review]
Thanks!
I've updated it, squashed commits and set manpage documentation dependent on requested cli version

**Review by kit-ty-kate — APPROVED** [review]
