### PR TITLE
switch install: fix multiple compiler candidates

### LINKED ISSUE #3874: creating local switch only works if there already is a switch
I wanted to start using local switches.
Locally, with several existing global switches (one being 4.07.1), `opam switch -y create ./ --deps-only` works fine (log says `installed ocaml-system.4.07.1`).
On travis-ci, after `opam init -y -a --bare` (without having any switches installed), it fails with `No available version of ocaml-base-compiler satisfies the constraints` ([see log](https://travis-ci.com/goblint/analyzer/jobs/207815684#L536)).
There it only works if I specify a compiler version, e.g., `opam switch -y create ./ --deps-only ocaml-base-compiler.4.07.1`.
I would expect that local switches also install a compiler if there is none yet.
The version constraint in the `opam` file is `"ocaml" {>= "4.04.1" & < "4.08"}`.

### PR DESCRIPTION
**Pull request by rjbou**
On local switch creation, if no compiler is specified or & single infered, there is the choice between several candidates that comply with the local opam file, defined as a conjunction that leads to an unresolvable solver request.

Fixes #3874

### CODE REVIEW

**Comment by rjbou** [comment]
ping @AltGr especially for 62fcdb9

File: src/client/opamCommands.ml [hunk 1]
```diff
@@ -2083,19 +2084,24 @@ let switch =
       | packages, _ -> packages
     in
     let compiler_packages rt ?repos switch compiler_opt =
+      let open OpamStd.Option.Op in
+      let single_lst p = (p >>| (fun x -> [x])) +! [] in
```
Comment (AltGr) [inline src/client/opamCommands.ml]: Worth adding `OpamStd.Option.to_list` maybe ? :D
(which made its way into 4.08.0 IIRC)

Comment (dra27) [reply src/client/opamCommands.ml]: `Option.to_list` is indeed in 4.08.0

Comment (rjbou) [reply src/client/opamCommands.ml]: A good occasion actually :)
