### PR TITLE
installer script: Ensure AppArmor supports the 4.0 abi when dealing with AppArmor

### LINKED ISSUE #6763: apparmor: abi/4.0 does not exist on Debian
On my (I believe) standard Debian bookworm, which is the current oldstable, AppArmor does not contain `abi/4.0`. As a result the parsing fails:
```
/etc/apparmor.d$ sudo apparmor_parser -Q /etc/apparmor.d/opam-local
AppArmor parser error for /etc/apparmor.d/opam-local in profile /etc/apparmor.d/opam-local at line 4: Could not open 'abi/4.0': No such file or directory
```

OTOH `/etc/apparmor.d/abi/3.0` exists. Is there a chance the required version could be downgraded? I tried changing the line by hand, but I got another error later, so the change is not trivial.

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes #6763 

@yakobowski would you be able to check this fix out and tell me if it solves your issue? (once the previously installed profile removed of course)

### CODE REVIEW

File: shell/install.sh [hunk 1]
```diff
@@ -766,7 +766,7 @@ xsudo install -m 755 "$TMP/$OPAM_BIN" "$BINDIR/opam"
 echo "## opam $VERSION installed to $BINDIR"
 
 # Handle AppArmor which makes it impossible to use bwrap (e.g. Ubuntu >= 24.04)
-if [ -d /etc/apparmor.d ] && [ "$(aa-enabled 2> /dev/null)" = Yes ]; then
+if [ -f /etc/apparmor.d/abi/4.0 ] && [ "$(aa-enabled 2> /dev/null)" = Yes ]; then
```
Comment (rjbou) [inline shell/install.sh:769]: Are we sure that it will work on targeted ubuntu distro, ie that we won't face apparmor with ABI 3.0 confining bwrap ?
If it could be the case, we need to have also a profile for ABI 3.0.

Comment (kit-ty-kate) [reply shell/install.sh:769]: Ubuntu 24.04 (first version of Ubuntu to ship with AppArmor enabled by default) ships apparmor 4.0.1 as mentioned in https://github.com/ocaml/opam/issues/5968#issuecomment-2384069633 and apparmor 3.x doesn't seem to have been a problem ever before, i suspect it wasn't as restrictive.

```
$ docker run --rm -it ubuntu:24.04
root@d022a2ea4fb1:/# apt update
Get:1 http://ports.ubuntu.com/ubuntu-ports noble InRelease [256 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports noble-updates InRelease [126 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports noble-backports InRelease [126 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports noble-security InRelease [126 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports noble/multiverse arm64 Packages [274 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports noble/universe arm64 Packages [19.0 MB]
Get:7 http://ports.ubuntu.com/ubuntu-ports noble/restricted arm64 Packages [113 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports noble/main arm64 Packages [1776 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports noble-updates/restricted arm64 Packages [3834 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports noble-updates/multiverse arm64 Packages [34.0 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports noble-updates/universe arm64 Packages [1864 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports noble-updates/main arm64 Packages [2075 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports noble-backports/main arm64 Packages [49.4 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports noble-backports/universe arm64 Packages [33.9 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports noble-security/main arm64 Packages [1691 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports noble-security/universe arm64 Packages [1153 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports noble-security/multiverse arm64 Packages [34.3 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports noble-security/restricted arm64 Packages [3591 kB]
Fetched 36.2 MB in 5s (6763 kB/s)                             
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@d022a2ea4fb1:/# apt install apparmor
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  apparmor-profiles-extra apparmor-utils
The following NEW packages will be installed:
  apparmor
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 622 kB of archives.
After this operation, 3441 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports noble-updates/main arm64 apparmor arm64 4.0.1really4.0.1-0ubuntu0.24.04.4 [622 kB]
Fetched 622 kB in 0s (3287 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package apparmor.
(Reading database ... 4376 files and directories currently installed.)
Preparing to unpack .../apparmor_4.0.1really4.0.1-0ubuntu0.24.04.4_arm64.deb ...
Unpacking apparmor (4.0.1really4.0.1-0ubuntu0.24.04.4) ...
Setting up apparmor (4.0.1really4.0.1-0ubuntu0.24.04.4) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 79.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC entries checked: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.38.2 /usr/local/share/perl/5.38.2 /usr/lib
/aarch64-linux-gnu/perl5/5.38 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl-base /usr/lib/aarch64-linux-gnu/perl/5.38 /usr/share/perl/5.38 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.p
m line 8.)
debconf: falling back to frontend: Teletype
root@d022a2ea4fb1:/# ls /etc/apparmor.d/abi/
3.0  4.0  kernel-5.4-outoftree-network  kernel-5.4-vanilla
```

**Comment by yakobowski** [comment]
@kit-ty-kate I think it worked. I checked out the branch and ran `shell/install.sh`, the installation went well. There was not a single mention of apparmor in the log, but that seems consistent with the state of the script.
