### PR TITLE
Fix lock behaviour on pinning

### LINKED ISSUE #4313: `opam install --locked` silently ignores the --locked option
The behavior of `install --locked` is really confusing, especially because there's no indication that anything is wrong.

The thing I would expect to work:

```bash
# Pin package(s) in the current repo but don't install deps yet
opam pin add -y -n .
# Install depexts
opam depext mypackage -y
# Now install deps
opam install . -y --locked
```

In this case, the `--locked` argument does absolutely nothing and the deps are installed only using mypackage.opam.

After reading `opam install --help`, I realized that `--locked` only works for with `opam pin`:

```bash
# Pin package(s) in the current repo but don't install deps yet
opam pin add -y -n .
# Install depexts
opam depext mypackage -y
# Now install deps in a really convoluted way
opam pin remove -y mypackage
opam pin add -y --locked .
```

There are two things I'd propose changing:

1. Please make `opam install --locked` use the lock file
2. Until (1) is done, make `opam install --locked` return an error message instead of silently ignoring the argument

### PR DESCRIPTION
**Pull request by rjbou**
* Fix pinned status display in action list
* Fix repin of locked pins when no changes is detected
fix #4313

### CODE REVIEW

File: src/client/opamAuxCommands.ml [hunk 1]
```diff
@@ -304,11 +309,13 @@ let autopin_aux st ?quiet ?(for_view=false) ?recurse ?subpath atom_or_local_list
           &&
           (* For `opam show`, we need to check does the opam file changed to
              perform a simulated pin if so *)
-          (not for_view ||
+          ((not for_view && not locked) ||
```
Comment (AltGr) [inline src/client/opamAuxCommands.ml:312]: I wonder why `not_locked` needs to be checked here, it should already have affected the contents of either opam file (and I would expect the situation to be symmetric w.r.t. the flag ?)
