### PR TITLE
Format upgrade fix: remove missing switches from config file

### LINKED ISSUE #4713: The layout update should not fail even if the installed-switches are incorrect
If you run `rm -rf _opam` insetad of `opam switch remove .` to delete a local switch, opam cannot update the config properly. If you try to update the layout under these conditions, you will get an error like the following, but it should not occur or it should be more friendly.

```
~
❯ opam update --upgrade
This version of opam requires an update to the layout of /home/smorimoto/.opam from version 2.1~alpha to version
2.1~rc, which can't be reverted.
You may want to back it up before going further.
Perform the update and continue? [Y/n] y
Fatal error:
Sys_error("/home/smorimoto/src/github.com/REDACTED/REDACTED/_opam/.opam-switch/switch-config: No such file or directory")
```

### PR DESCRIPTION
**Pull request by rjbou**
* Fix format upgrade when there is missing local switches in the config file
* Fix not recorded local switch handling, with format upgrade
* Set opam root version to 2.1
* Update tests with 2.1, local switch (recorded and not)
fix #4713

### CODE REVIEW

File: src/state/opamFormatUpgrade.ml [hunk 1]
```diff
@@ -1210,6 +1219,24 @@ let as_necessary requested_lock global_lock root config =
...
+    let tostr sws =
+      OpamStd.Format.pretty_list
+        (List.map (OpamSwitch.to_string @> OpamConsole.colorise `bold) sws)
+    in
+    let switches = function [_] -> "" | _ -> "es" in
+    if global <> [] then
+      OpamConsole.warning "Broken global switch%s %s"
+        (switches global) (tostr global);
+    if not on_the_fly && local <> []then
+      OpamConsole.note "Removing local switch%s %s as it no longer exists"
```
Comment (dra27) [inline src/state/opamFormatUpgrade.ml:1236]: The plural form changes the sentence slightly: "as _they_ no longer _exist_"

File: src/state/opamFormatUpgrade.ml [hunk 2]
```diff
@@ -1210,6 +1219,24 @@ let as_necessary requested_lock global_lock root config =
...
+    let local, global =
+      List.partition OpamSwitch.is_external missing_switches
+    in
+    let tostr sws =
+      OpamStd.Format.pretty_list
+        (List.map (OpamSwitch.to_string @> OpamConsole.colorise `bold) sws)
+    in
+    let switches = function [_] -> "" | _ -> "es" in
+    if global <> [] then
+      OpamConsole.warning "Broken global switch%s %s"
```
Comment (dra27) [inline src/state/opamFormatUpgrade.ml:1233]: The message in the reftests looks strange because it creates "Broken global switch missing". These switches are also removed, though, so could the sentence be in the same form as for local switches (I agree it's a warning - the user can reasonably delete local switches by accident, but manually deleting a global switch is naughty!).

"Removing references to broken global switch%s %s as it/they no longer exists/exist"?

**Review by dra27 — COMMENTED** [review]
Possible message tweaks

File: src/state/opamFormatUpgrade.ml (hunk 2 above)
Comment (rjbou) [reply src/state/opamFormatUpgrade.ml:1233]: I intentionally didn't use the same wording of 'removal' because this is printed even in light upgrades (non blocking), users won't understand why a switch will be removed when they just want to install a package for example. But yes, better have two different sentences : 
* light: _Broken global switch%s %s_ , or use the same as in https://github.com/OCamlPro/opam/blob/master/src/state/opamSwitchState.ml#L30 _Removing local switch %s as it no longer exists_
* hard: _Removing references to broken global switch%s %s as it/they no longer exists/exist_ or the same as local ones
?

File: src/state/opamFormatUpgrade.ml [hunk 3]
```diff
@@ -1189,6 +1228,33 @@ let as_necessary requested_lock global_lock root config =
...
+    in
+    (if not on_the_fly && global <> [] then
+       let switches, existence = sentences global in
+       OpamConsole.warning "Removing global switch%s %s as %s"
+         switches (tostr global) existence);
+    (if not on_the_fly && local <> [] then
+       let switches, existence = sentences local in
+       OpamConsole.note "Removing local switch%s %s as %s"
+         switches (tostr local) existence);
+    config
```
Comment (AltGr) [inline src/state/opamFormatUpgrade.ml:1255]: No need for a message, it's silently handled in the normal (no update) case (it's an expected workflow that you just `rm -rf` source dirs).

File: src/state/opamFormatUpgrade.ml [hunk 4]
```diff
@@ -1054,10 +1054,26 @@ let v2_1_alpha2 = OpamVersion.of_string "2.1~alpha2"
 (* config & sw config downgrade opam-version to 2.0 and add opam root version *)
 let v2_1_rc = OpamVersion.of_string "2.1~rc"
 
-let _v2_1 = OpamVersion.of_string "2.1"
+let v2_1 = OpamVersion.of_string "2.1"
 
 let from_2_0_to_2_1_alpha _ conf = conf
 
+let get_unrecorded_local_switch conf =
```
Comment (AltGr) [inline src/state/opamFormatUpgrade.ml:1061]: I am not sure about this: format upgrade is not expected to depend on CWD ?

The proper way to do it would be to do the update lazily but it's probably not practical...

Another point: it's forbidden to touch an external switch if its opamroot doesn't match the current one, so that must be checked.

**Review by AltGr — CHANGES_REQUESTED** [review]
Nice, thanks!

I am not sure about the unrecorded switches part though, we'd need to scan the whole disk for it to be consistent.

File: src/state/opamStateConfig.ml [hunk 5]
```diff
@@ -281,12 +281,44 @@ module Repos = struct
...
-  OpamPath.Switch.switch_config root switch |>
-  OpamFile.Switch_config.BestEffort.read_opt |> function
+  let f = OpamPath.Switch.switch_config root switch in
+  match OpamFile.Switch_config.BestEffort.read_opt f with
   | None -> false
   | Some conf -> conf.OpamFile.Switch_config.opam_root = Some root
+  | exception (OpamPp.Bad_version _ as e) ->
+    match OpamFile.Config.raw_root_version (OpamPath.config root) with
+    | None -> raise e
+    | Some _ ->
```
Comment (rjbou) [inline src/state/opamStateConfig.ml:315]: Should it be constrained to root version `2.1~rc/2.1` ?

Comment (dra27) [reply src/state/opamStateConfig.ml:315]: I think so - doesn't this become a problem in future if it gets `opam-root-version: "2.2"`?

Comment (rjbou) [reply src/state/opamStateConfig.ml:315]: With a `2.2` opam root, the local switch upgrade won't be triggered, yes.

Comment (dra27) [reply src/state/opamStateConfig.ml:315]: Ah, of course, the whole thing is in the exception for an incorrect version.

File: src/state/opamStateConfig.ml [hunk 6]
```diff
@@ -281,12 +281,44 @@ module Repos = struct
...
+    { opamfile with
+      file_contents =
+        List.map (fun item ->
+            match item.pelem with
+            | Variable (({pelem = "opam-version"; _} as opam_v),
+                        ({pelem = String "2.1"; _} as v)) ->
+              { item with
+                pelem = Variable ({opam_v with pelem = "opam-version"},
+                                  {v with pelem = String "2.0"})}
+            | _ -> item) opamfile.file_contents}
```
Comment (AltGr) [inline src/state/opamStateConfig.ml:299]:
```suggestion
            | _ -> item)
          opamfile.file_contents }
```

File: src/state/opamStateConfig.ml (hunk 5 above)
Comment (AltGr) [reply src/state/opamStateConfig.ml:315]: Since this fix is only necessary for intermediate dev versions, I'd say we remove it from 2.2 or at least 2.3: it'll keep the upgrade code more maintainable and we can reasonably assume anyone who tried one of the affected versions switched to the release in the meantime ?

File: src/state/opamStateConfig.mli [hunk 7]
```diff
@@ -137,3 +137,9 @@ module Repos : sig
   val safe_read:
     ?lock_kind: 'a lock -> 'b global_state -> OpamFile.Repos_config.t
 end
+
+(* Raw read an switch config to downgrade its [opam-version] from 2.1 to 2.0.
+   It is necessary to handle opam root and switch upgrade from 2.1
+   intermediates roots to 2.1. *)
```
Comment (AltGr) [inline src/state/opamStateConfig.mli:143]: I'd add more context here to explain _why_ it is necessary ? E.g. "This allows a workaround for a bug in versions 2.1~xx which wrongly updated the declared switch versions, requiring that we fix it during [OpamFormatUpdate] from these specific intermediate versions"

File: tests/reftests/run.ml [hunk 8]
```diff
@@ -476,6 +484,65 @@ let run_test ?(vars=[]) ~opam t =
           List.fold_left
             (fun vars (v, r) -> (v, r) :: List.filter (fun (w, _) -> v <> w) vars)
             vars bindings
+        | Cat files ->
+          let print_opamfile header file =
```
Comment (AltGr) [inline tests/reftests/run.ml:488]: This probably deserves to be a top-level function :grin:

**Review by AltGr — APPROVED** [review]
Only minor (mostly style and code doc) comments

File: src/state/opamStateConfig.ml (hunk 5 above)
Comment (rjbou) [reply src/state/opamStateConfig.ml:315]: it's unregistered local switch, they can stay around for a while without noticing

File: tests/reftests/run.ml (hunk 8 above)
Comment (rjbou) [reply tests/reftests/run.ml:488]: it will be removed from `run.ml` to be an outside program
