### PR TITLE
Fix behaviour when stdout gets closed

### LINKED ISSUE #4216: Sys_error("Broken pipe") printed to console on `opam list`
On `2.1.0~alpha`, piping `opam list` into a process that breaks the pipe causes a "Fatal error" message to be printed to the console. The exit code is 0 regardless.

```
ᐅ opam list | head -n 5
# Packages matching: installed
# Name                  # Installed  # Synopsis
asetmap                 0.8.1        Alternative, compatible, OCaml standard library Sets and Maps
astring                 0.8.3        Alternative String module for OCaml
base                    v0.13.2      Full standard library replacement for OCaml
Fatal error: exception Sys_error("Broken pipe")

ᐅ echo $?
0
```

I would expect `opam` to handle a `SIGPIPE` here with no error message.

### PR DESCRIPTION
**Pull request by AltGr**
Restore the sigpipe handler before exiting, to prevent the finaliser
from crashing on flushes.

Closes #4216: the behaviour on that example is now to exit with code
141, and without an error message.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you add a one or two line cram test to the testsuite?

**Comment by AltGr** [comment]
Hmm I can try but we'll have to resort to using shell-pipes and that probably will break on Windows. @dra27 what do you think ?

File: src/client/opamCliMain.ml [hunk 1]
```diff
@@ -358,7 +358,8 @@ let rec main_catch_all f =
          "Update done, please now retry your command.\n";
        exit (OpamStd.Sys.get_exit_code `Aborted))
   | e ->
-    Sys.set_signal Sys.sigpipe Sys.Signal_default;
+    try Sys.set_signal Sys.sigpipe Sys.Signal_default
+    with Invalid_argument _ -> ()
```
Comment (kit-ty-kate) [inline src/client/opamCliMain.ml:362]:
```suggestion
    (try Sys.set_signal Sys.sigpipe Sys.Signal_default
     with Invalid_argument _ -> ());
```

Comment (AltGr) [reply src/client/opamCliMain.ml]: huh thanks, seems I was a little too hurried :sweat_smile:

**Comment by kit-ty-kate** [comment]
Tests showing the bug added in https://github.com/ocaml/opam/pull/5022

**Comment by kit-ty-kate** [comment]
This needs to be applied for the tests to pass
```
commit d17de7079cb277081274308fafc4ef9a5afa8164 (HEAD -> broken-pipe)
Author: Kate <kit.ty.kate@disroot.org>
Date:   Wed Jan 26 09:50:03 2022 +0000

    Show that https://github.com/ocaml/opam/issues/4216 is now fixed

diff --git a/tests/cram/unix/list.t b/tests/cram/unix/list.t
index 113085860..99c2fdf0b 100644
--- a/tests/cram/unix/list.t
+++ b/tests/cram/unix/list.t
@@ -1,6 +1,5 @@
 Test https://github.com/ocaml/opam/issues/4216
   $ export OPAMROOT=./opamroot
   $ opam init --bare -n git+https://github.com/ocaml/opam-repository.git#0ec9bbf73a91b8e90b15bb11735859c9552a9888 > /dev/null
-  $ OCAMLRUNPARAM=-b opam list --depends-on dune -s --all-versions | head -n1
+  $ opam list --depends-on dune -s --all-versions | head -n1
   0install.2.14
-  Fatal error: exception Sys_error("Broken pipe")
```

**Review by kit-ty-kate — APPROVED** [review]

**Comment by AltGr** [comment]
Thanks for the rebase/test update @rjbou
