### PR TITLE
`OPAMSWITCH` and `OPAMROOT` reverts

### LINKED ISSUE #5696: opam 2.2.0~alpha2: OPAMSWITCH does not work anymore
The reason is that the shell hook resets `OPAMSWITCH` to the empty string as soon as it is set. This is because `opam env --shell=zsh --readonly` (my shell is zsh) prints `OPAMSWITCH=''; export OPAMSWITCH;` as the first line.

Before, the same command did not print `OPAMSWITCH`. This seems to be a consequence of https://github.com/ocaml/opam/pull/5417.

### PR DESCRIPTION
**Pull request by rjbou**
~Store old `OPAMSWITCH` in last env file, in order to revert it properly~
Don't store `OPAMSWITCH` & `OPAMROOT` in the last environment file, like that they are not reverted. They are set with `--set-switch` and `--set-root`, they are meant to remain in the shell environment.

fixes #5696

queued on #5715 for windows ci

### CODE REVIEW

**Comment by rjbou** [comment]
CI issue
```diff
@@ -96,11 +96,20 @@ opam sw show
 ### sh unset-opamswitch.sh opam
 foo
 OPAMSWITCH='bar'; export OPAMSWITCH;
-OPAMSWITCH=''; export OPAMSWITCH;
-bar
+unset-opamswitch.sh: line 13: $'\r': command not found
+unset-opamswitch.sh: line 13: $'\r': command not found
+unset-opamswitch.sh: line 13: $'\r': command not found
+unset-opamswitch.sh: line 13: $'\r': command not found
+unset-opamswitch.sh: line 13: $'\r': command not found
+foo
```
will be resolved by #5715

**Comment by rjbou** [comment]
Other solution could be to not store `OPAMSWITCH` in last env file at all

**Comment by rjbou** [comment]
Updated!

File: src/core/opamConsole.ml [hunk 1]
```diff
@@ -511,13 +521,13 @@ let clear_status =
 
 let print_message =
   if Sys.win32 then
-    fun ch fmt ->
+    fun ?(stdout=stdout) ch fmt ->
       flush (if ch = `stdout then stderr else stdout);
       clear_status ();
       (* win32_print_message *always* flushes *)
       Printf.ksprintf (win32_print_message ch) fmt
```
Comment (dra27) [inline src/core/opamConsole.ml:528]: `win32_print_message` needs a `~stdout` parameter, too (sorry - these functions have ended up a bit of a mess over time... I think just adding that parameter here will be easier than trying to straighten out all the old VT100 emulation code)

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks!
