### PR TITLE
opam env: fix carriage return on Cygwin shell

### LINKED ISSUE #5684: opam.2.2~alpha2 env error on Windows 10 / 11
Running opam env eval on Windows includes extra chars. It seems to be choosing the wrong encoding for the active shell. I am running this in a cygwin64 terminal on either Windows 10 or 11. 
```
tmcgilchrist@vdi7 ~/code/ocaml/ocaml-grpc
$  eval $(opam env --switch=5.0)
-bash: $'\r': command not found
-bash: $'\r': command not found
-bash: $'\r': command not found
-bash: $'\r': command not found
-bash: $'\r': command not found
-bash: $'\r': command not found

tmcgilchrist@vdi7 ~/code/ocaml/ocaml-grpc
$ opam --version
2.2.0~alpha2

tmcgilchrist@vdi7 ~/code/ocaml/ocaml-grpc
$ opam config report
# opam config report
# opam-version         2.2.0~alpha2
# self-upgrade         no
# system               arch=x86_64 os=win32 os-distribution=cygwin os-version=10.0.22621
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 3
# repositories         3 (version-controlled)
# pinned               0
# current-switch       5.0
# invariant            ocaml = 5.0.0 & ocaml-option-mingw
# compiler-packages    flexdll.0.42, ocaml-option-mingw.1, ocaml-variants.5.0.0+pr11846
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       C:/Users/tmcgilchrist/AppData/Local/opam/5.0/lib/ocaml/stublibs;C:/Users/tmcgilchrist/AppData/Local/opam/5.0/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       5.0.0+pr11846
```

Manually removing the `\r` like so ` eval $(opam env --switch=5.0 | tr -d '\r')` fixes the issue.

### PR DESCRIPTION
**Pull request by rjbou**
fix #5684

### CODE REVIEW

File: src/core/opamConsole.ml [hunk 1]
```diff
@@ -37,6 +37,14 @@ let disp_status_line () =
   | `Never -> false
   | `Auto -> OpamStd.Sys.tty_out && (color () || not (Lazy.force dumb_term))
 
+let disable_carriage_return =
+  if Sys.win32 && not OpamStd.Sys.tty_out then
+    fun () ->
+      set_binary_mode_out stdout true;
+      set_binary_mode_out stdout true
```
Comment (kit-ty-kate) [inline src/core/opamConsole.ml:44]: why is the same thing done twice?

Comment (rjbou) [reply src/core/opamConsole.ml:44]: because it's an error!

Comment (rjbou) [reply src/core/opamConsole.ml:44]:
```suggestion
      set_binary_mode_out stdout true;
      set_binary_mode_out stderr true
```

File: master_changes.md [hunk 2]
```diff
@@ -158,3 +161,4 @@ users)
   * `OpamSystem.mk_temp_dir`: resolve real path with `OpamSystem.real_path` before returning it [#5654 @rjbou]
   * `OpamSystem.resolve_command`: in command resolution path, check that the file is not a directory and that it is a regular file [#5606 @rjbou - fix #5585 #5597 #5650 #5626]
   * `OpamStd.Config.env_level`: fix level parsing, it was inverted (eg, "no" gives level 1, and "yes" level 0) [#5686 @smorimoto]
+  * `OpamConsole`: add `disable_carriage_return` to disable automatic addition of carriage return (`set_bynari_mode_out`) on stdou & stderr on Windows if out is not tty [#5715 @rjbou]
```
Comment (emillon) [inline master_changes.md:164]:
```suggestion
  * `OpamConsole`: add `disable_carriage_return` to disable automatic addition of carriage return (`set_binary_mode_out`) on stdout & stderr on Windows if out is not tty [#5715 @rjbou]
```

Comment (rjbou) [reply master_changes.md]: thanks

**Review by kit-ty-kate — APPROVED** [review]

File: src/core/opamConsole.ml [hunk 3]
```diff
@@ -22,6 +22,20 @@ let dumb_term = lazy (
...
+  if (Sys.win32 || Sys.cygwin) && not OpamStd.Sys.tty_out then
+    let old_value_out = OpamStubs.getBinaryMode stdout in
+    let old_value_err = OpamStubs.getBinaryMode stderr in
+    if old_value_err && old_value_out then fun k -> k () else
+    fun k ->
+      set_binary_mode_out stdout true;
+      set_binary_mode_out stderr true;
+      k ();
+      set_binary_mode_out stdout old_value_out;
+      set_binary_mode_out stderr old_value_err
```
Comment (kit-ty-kate) [inline src/core/opamConsole.ml:35]: I think we might want to add a mutex here in case the code is being used in parallel

File: src/stubs/win32/opamWindows.c [hunk 4]
```diff
@@ -778,3 +779,28 @@ CAMLprim value OPAMW_GetConsoleWindowClass(value unit)
...
+ * mode, true if binary, false if text.
+ * It uses [caml_channel_binary_mode]. */
+CAMLprim value OPAMW_GetBinaryMode(value vchannel) {
+
+  CAMLparam1 (vchannel);
+  struct channel *channel = Channel(vchannel);
+
+  int i;
+
+#if OCAML_VERSION_MAJOR >= 5 && OCAML_VERSION_MINOR >= 2
```
Comment (emillon) [inline src/stubs/win32/opamWindows.c:793]: that comparison is incorrect, it will return false for ocaml 6.0 and 6.1 (I know...).
I believe that the correct way if `OCAML_VERSION >= 50200`

Comment (rjbou) [reply src/stubs/win32/opamWindows.c:796]:
```suggestion
#if OCAML_VERSION_MAJOR >= 50200
```

Comment (rjbou) [reply src/stubs/win32/opamWindows.c]: well spotted, thanks!

File: src/stubs/win32/opamWindows.c [hunk 5]
```diff
@@ -778,3 +782,28 @@ CAMLprim value OPAMW_GetConsoleWindowClass(value unit)
...
+  caml_channel_lock(channel);
+#else
+  Lock(channel);
+#endif
+  i = caml_channel_binary_mode(channel);
+#if OCAML_VERSION_MAJOR >= 50200
+  caml_channel_unlock(channel);
+#else
+  Unlock(channel);
+#endif
```
Comment (dra27) [inline src/stubs/win32/opamWindows.c:806]: which then allows:
```suggestion
  Lock(channel);
  i = caml_channel_binary_mode(channel);
  Unlock(channel);
```

**Review by dra27 — COMMENTED** [review]
Possible C simplification

File: src/stubs/win32/opamWindows.c (hunk 5 above)
Comment (rjbou) [reply src/stubs/win32/opamWindows.c:806]: I like that!

**Comment by rjbou** [comment]
Updated @kit-ty-kate !

**Comment by rjbou** [comment]
todo : Update with cloning file descriptors instead of mutex

**Comment by kit-ty-kate** [comment]
Thanks!
