### PR TITLE
depext fixes: unavailable reason, pin, depext-bypass, list

### LINKED ISSUE #4176: Missing "depext unavailable" message
This is fine:
```
~ $ opam install conf-pkg-config
[ERROR] Package conf-pkg-config depends on the unavailable system package 'pkgconfig'. You can use `--no-depexts' to attempt installation anyway.
```
But the info is missing here:
```
~ $ opam install conf-libcurl
The following dependencies couldn't be met:
  - conf-libcurl -> conf-pkg-config

No solution found, exiting
```

### LINKED ISSUE #4177: depext-bypass not always updated as expected
It seems that `opam install foo --no-depexts` doesn't properly store the exceptions:
```
 $ opam install conf-pkg-config --no-depexts
The following actions will be performed:
  - install conf-pkg-config 1.1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed conf-pkg-config.1.1
Done.
# Run eval $(opam env) to update the current shell environment
$ opam upgrade --show
[WARNING] Opam package conf-pkg-config.1.1 depends on the following system package that can no longer be found: pkgconfig
```

### LINKED ISSUE #4189: [2.1.0-alpha] pinning drop newly modified depext
```
$ opam pin edit conf-bmake
Package conf-bmake is not pinned. Edit as a new pinning to version 1.0? [Y/n] y
Press enter to start "vim" (this can be customised by setting EDITOR or OPAMEDITOR)... 
      ## change to an inexistant package
Proceed anyway ('no' will re-edit)? [Y/n] y
You can edit this file again with "opam pin edit conf-bmake", export it with "opam show conf-bmake --raw"
conf-bmake is now pinned locally (version 1.0)
The following actions will be performed:
  ∗ install conf-bmake 1.0*

The following system packages will first need to be installed:
    bmake
Do you want to continue? [Y/n] n
```

### LINKED ISSUE #4205: [opam.2.1.0~alpha] --no-depexts missing from opam list
Now that `opam list --installable` also check depexts, there should be a way to switch the depexts check off, similar to the `--no-depexts` option for the `opam install` command.

For example, with opam 2.0 we have:
```
$ opam list --installable
[...]
conf-llvm.4.0.0
[...]
```
but with opam 2.1, `conf-llvm.4.0.0` does not show up. It would be good to have the option to skip this new check.

### PR DESCRIPTION
**Pull request by rjbou**
* add depext check to unavailable reason, on the same behavior as in `check_availability`, by displaying the max element depexts. fix #4176
* add depext handling on new pinned packages fix #4189 
* add `depext-bypass`  as a modifiable field in switch config fix #4177
* fix old opam option format in messages
* fix opam list depext handling fix #4205

### CODE REVIEW

File: src/client/opamSolution.ml [hunk 1]
```diff
@@ -364,7 +359,15 @@ let parallel_apply t ~requested ?add_roots ~assume_built ?(force_remove=false)
       else !invariant_ref
     in
     if bypass <> !bypass_ref || invariant <> !invariant_ref then
-      (bypass_ref := bypass;
+      (if bypass <> !bypass_ref then
+         (let spkgs = OpamSysPkg.Set.Op.(bypass -- !bypass_ref) in
+          OpamConsole.note
+            "Add system package%s %s to switch 'depext-bypass' field"
```
Comment (AltGr) [inline src/client/opamSolution.ml:365]:
```suggestion
            "The bypass of system package %s has been registered in this switch. You \
             can use `opam option depext-bypass-=%s' to revert."
```

File: src/state/opamSwitchState.ml [hunk 2]
```diff
@@ -997,7 +1008,14 @@ let unavailable_reason st ?(default="") (name, vformula) =
         (OpamConsole.colorise `bold
            (OpamFileTools.dep_formula_to_string st.switch_invariant))
     else
-      default
+    match depexts_unavailable st (OpamPackage.Set.max_elt candidates) with
+    | Some missing ->
+      Printf.sprintf
+        "depends on the unavailable system package '%s', you \
+         can use `--assume-depexts' to attempt installation anyway."
```
Comment (AltGr) [inline src/state/opamSwitchState.ml:1015]:
```suggestion
        "depends on the unavailable system package '%s'. Use \
         `--assume-depexts' to attempt installation anyway."
```

File: master_changes.md [hunk 3]
```diff
@@ -6,8 +6,24 @@ note.
...
 ## Switch
   * Fix Not_found with `opam switch create . --deps` [#4151 @AltGr]
+  * Add missing depext to unavailable reasons [#4194 @rjbou - fix #4176]
+
+
+## Pin
+  * Add depext handling on new pinned packages [#4194 @rjbou - fix #4189]
+
+## Option
+  * Fix old format in messages [#4194 @rjbou]
```
[the remark this answers is not in the document]
Comment (rjbou) [reply master_changes.md:16]: This master changelog is not meant to be kept as is in the release note / final changelog. I prefer to have the most precise master changelog and clean it, than having incomplete one and try to find the information afterwards..

File: src/client/opamClient.ml [hunk 4]
```diff
@@ -1377,16 +1377,49 @@ module PIN = struct
...
+               | Some missing ->
+                 OpamConsole.error
+                   "Package %s depends on the unavailable system package '%s'.\
+                    You can use `--no-depexts' to attempt installation anyway."
+                   (OpamPackage.to_string pkg)
+                   (OpamStd.List.concat_map " " OpamSysPkg.to_string
+                      (OpamSysPkg.Set.elements missing));
+                 false
+               | None -> true)
+             pkgs)
```
[the remark this answers is not in the document]
Comment (rjbou) [reply src/client/opamClient.ml]: In fact, it's `available_packages` and `sys_packages` that need to be updated, in the same way it's done in the switch state loading. cf. newer comment

File: src/client/opamClient.ml [hunk 5]
```diff
@@ -1378,16 +1378,39 @@ module PIN = struct
...
+                OpamPackage.Map.union (fun _ n -> n)
+                  (Lazy.force st.sys_packages)
+                  (OpamSwitchState.depexts_status_of_packages st pkgs)
+              )}
+        in
+        { st with available_packages = lazy (
+              OpamPackage.Set.filter (fun nv ->
+                  OpamSwitchState.depexts_unavailable st nv = None)
+                (Lazy.force st.available_packages)
+            )}
```
Comment (rjbou) [inline src/client/opamClient.ml:1412]: Same code thant in `OpamSwitchState.load`,  it's minimal, but we can add a function in that module for that kind of operations

File: src/client/opamCommands.ml [hunk 6]
```diff
@@ -532,9 +532,15 @@ let list ?(force_search=false) () =
       "Don't write anything in the output, exit with return code 0 if the list \
        is not empty, 1 otherwise."
   in
+  let no_depexts =
+    mk_flag ["no-depexts"]
+      "Disable external dependencies handling for the query. This can be used \
+       to list packages that are marked as unavailable because a not available \
+       system dependency."
```
Comment (AltGr) [inline src/client/opamCommands.ml:539]:
```suggestion
      "Disable external dependencies handling for the query. This can be used \
       to include packages that are marked as unavailable because of an unavailable \
       system dependency."
```
(with "list", at first I read it as, it lists _only_ those)

File: src/client/opamCommands.ml [hunk 7]
```diff
@@ -612,6 +619,39 @@ let list ?(force_search=false) () =
...
+                 >>= OpamSwitchState.depexts_unavailable st) with
+             | Some nf ->  OpamStd.String.Map.add str nf missing
+             | None -> missing
+             | exception Failure _ -> missing (* invalid package *)
+           ) OpamStd.String.Map.empty packages
+       in
+       if not (OpamStd.String.Map.is_empty drop_by_depexts) then
+         OpamConsole.note
+           "Some packages are unavailable because of their external dependencies. \
+            Use `--no-depexts` to bypass this check\n%s"
```
Comment (AltGr) [inline src/client/opamCommands.ml:648]:
```suggestion
           "Some packages are unavailable because of their external dependencies. \
            Use `--no-depexts' to show them anyway.\n%s"
```
