### PR TITLE
Fix empty conflict explanations

### LINKED ISSUE #4373: Unhelpful conflict messages
### *** Please add your unhelpful conflict message to this [discussion](https://github.com/ocaml/opam/discussions/5130) ***
---

While trying to install `expect.0.0.6` on OCaml 4.12:
```
[ERROR] Package conflict!
No solution found, exiting
  * No agreement on the version of ocaml:
    - (invariant) -> ocaml-variants = 4.12.0+trunk -> ocaml >= 4.12.0
    - expect >= 0.0.6 -> batteries -> ocaml < 4.00.0
    You can temporarily relax the switch invariant with `--update-invariant'
```
I would have expected:
```
    - expect >= 0.0.6 -> batteries -> ocaml < 4.12.0
```
as the latest version of `batteries` indicates.

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes #4373

### CODE REVIEW

File: src/solver/opamCudf.ml [hunk 1]
```diff
@@ -848,7 +902,7 @@ let extract_explanations packages cudfnv2opam reasons : explanation list =
               Map.update pkg (CS.union chain) CS.empty acc
             in
             let ds = get deps p in
-            let dsc = ds %% all_conflicting in
+            let dsc = ds in
```
Comment (kit-ty-kate) [inline src/solver/opamCudf.ml:905]: it looks like this line alone also fixes the issue.. I’ll have a look

File: src/solver/opamCudf.ml [hunk 2]
```diff
@@ -969,6 +1026,9 @@ let extract_explanations packages cudfnv2opam reasons : explanation list =
         | _ -> false)
   in
   match explanations with
+  | [] ->
+    OpamConsole.error_and_exit `Internal_error
+      "Internal error while computing conflict explanations: sorry, please report."
```
Comment (AltGr) [inline src/solver/opamCudf.ml:1031]: In general a conflict is the end of story for opam commands... still, it feels weird to hard error out from a function which sole purpose is to print an informative message. Does returning the "internal error" code really matter here, or couldn't we print the error message but just return `[]` ?

File: src/solver/opamCudf.ml [hunk 3]
```diff
@@ -854,7 +908,10 @@ let extract_explanations packages cudfnv2opam reasons : explanation list =
               Map.update pkg (CS.union chain) CS.empty acc
             in
             let ds = get deps p in
-            let dsc = ds %% all_conflicting in
+            let dsc = match Hashtbl.length missing with
+              | 0 -> ds
+              | _ -> ds %% all_conflicting
+            in
```
Comment (AltGr) [inline src/solver/opamCudf.ml:914]: This feels a bit fragile; maybe we could at least check that there is no "missing" below `p` in the dep tree rather than in general ?

This said, it already avoids the very problematic issue of no messages at all, and thank you *a lot* for finding a workaround.

File: src/solver/opamCudf.ml (hunk 2 above)
Comment (kit-ty-kate) [reply src/solver/opamCudf.ml:1031]: Note: this is part of https://github.com/ocaml/opam/pull/4981.

Mmh, we could make it into `OpamConsole.error` instead but this would make opam print two different user direction:
```
[ERROR] Package conflict!
[ERROR] Internal error while computing conflict explanations: sorry, please report.
Sorry, no solution found: there seems to be a problem with your request.
```
I’d rather push users to report instead of making them try to fiddle with the request and maybe give up reporting.

**Comment by AltGr** [comment]
This may not be perfect, but already works around most problematic cases in practice, so I think it should be merged (once rebased). Thanks Kate!
