### PR TITLE
init: on windows, fix handling of 'git-location' when defined in init config

### LINKED ISSUE #5845: Windows: git-location in init config file is unused
Field `git-location` is defined in init config file, but it is not used for git location setup.
related to #5718

### PR DESCRIPTION
**Pull request by rjbou**
fixes #5845 

If `--git-location` is given and `git-location` is defined, priority goes to the one defined via CLI. Same with `--no-git-location`, it overrides `git-location` definition in config file.

### CODE REVIEW

File: src/client/opamClient.ml [hunk 1]
```diff
@@ -747,7 +747,25 @@ let windows_checks ?cygwin_setup ?git_location config =
...
   (* Git handling *)
-  let git_location : string option = git_for_windows_check ?git_location () in
+  let git_location =
+    match git_location, OpamFile.Config.git_location config with
+    | None, None -> None
+    | Some (Right ()), None -> Some (Right ())
+    | Some (Right ()), Some _ ->
+      OpamConsole.note
+        "As '--no-git-location' is given in argument, ignoring field \
+         'git-location' in init config file";
```
Comment (rjbou) [inline src/client/opamClient.ml:757]: Needs proof reading for clarity, understanding.

File: src/client/opamClient.ml [hunk 2]
```diff
@@ -747,7 +747,25 @@ let windows_checks ?cygwin_setup ?git_location config =
...
+      Some (Right ())
+    | Some (Left gl), None | None, Some gl -> Some (Left gl)
+    | Some (Left gl_cli), Some gl_config ->
+      OpamConsole.note
+        "Git location defined in init config file (opamrc, %s) and via CLI \
+         ('--git-location' option, %s). Keeping last one."
```
Comment (rjbou) [inline src/client/opamClient.ml:763]: Needs proof reading for clarity, understaanding.

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks!
