### PR TITLE
Remove -a include base packages to keep

### LINKED ISSUE #3461: opam remove -a sometimes fails
Possible errors:

```
$ opam remove -a travis-opam
Your request can't be satisfied:
  - Package ocaml is part of the base for this compiler and can't be changed

No solution found, exiting
```

Or 

```
opam remove -a travis-opam
Your request can't be satisfied:
  - Package base-ocamlbuild is part of the base for this compiler and can't be
    changed
```
(in https://travis-ci.org/ocaml/ocaml-ci-scripts/jobs/404983746)

It's easy to reproduce with:

```
$ opam init -a git://github.com/ocaml/opam-repository#2.0.0 --comp=4.02.3
$ opam pin add travis-opam --dev -y
$ opam remove -a travis-opam
```

### PR DESCRIPTION
**Pull request by rjbou**
This PR fixes #3461.

### CODE REVIEW

File: src/client/opamClient.ml [hunk 1]
```diff
@@ -1158,6 +1158,7 @@ let remove_t ?ask ~autoremove ~force atoms t =
     let to_keep =
       (if autoremove then t.installed_roots %% t.installed else t.installed)
       -- to_remove -- full_orphans -- orphan_versions
+      ++ universe.u_base (* includes base packages of the universe *)
     in
```
Comment (AltGr) [inline src/client/opamClient.ml]: I believe `universe.u_base` should be on the left of the `--`: otherwise a user specifying a base package to be removed could be silently ignored ?

Also... tautological comment ? ;)
