### PR TITLE
Unset VC detection at 'pin add' by default

### LINKED ISSUE #2015: Pinning workflow not detecting preexisting opam file in 1.2.1
I have an `opam` file in this new package, but then pin ignores it.

```
$ opam pin add lterm-progress-bar .
Package lterm-progress-bar does not exist, create as a NEW package ? [Y/n] y
lterm-progress-bar is now git-pinned to /Users/avsm/src/git/avsm/ocaml-progress-bar
[NOTE] Pinning in mixed mode: OPAM will use tracked files in the current working
       tree from /Users/avsm/src/git/avsm/ocaml-progress-bar. If this is not what you want, pin to a given branch (e.g.
       /Users/avsm/src/git/avsm/ocaml-progress-bar#HEAD)

[lterm-progress-bar] /Users/avsm/src/git/avsm/ocaml-progress-bar already up-to-date

Invalid opam file:
    error: File format error: at ~/.opam/system/overlay/lterm-progress-bar/opam_:9:11, Bad url format ""
Errors in /Users/avsm/.opam/system/overlay/lterm-progress-bar/opam, retry editing ? [Y/n] n
[ERROR] No valid metadata available.
lterm-progress-bar is now unpinned from git /Users/avsm/src/git/avsm/ocaml-progress-bar
```

It brings up an editor, despite there being an `opam` file in the current directory...

### PR DESCRIPTION
**Pull request by AltGr**
and rewrite documentation accordingly

Closes #2015

### CODE REVIEW

File: src/client/opamArg.ml [hunk 1]
```diff
@@ -1525,8 +1528,14 @@ let pin ?(unpin_only=false) () =
     mk_flag ["e";"edit"] "With $(opam pin add), edit the opam file as with \
                           `opam pin edit' after pinning." in
   let kind =
-    let help = "Set the kind of pinning. Must be one of version, \
-                path, git, hg or darcs." in
+    let help =
+      "Sets the kind of pinning. Must be one of $(i,version), $(i,path), \
+       $(i,git), $(i,hg), $(i,darcs) or $(i,auto). \
```
Comment (dbuenzli) [inline src/client/opamArg.ml]: Since cmdliner 0.9.6 you can use [`Arg.doc_alts_enum`](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALdoc_alts_enum) on `kinds` for rendering that kind of sentence.

File: src/client/opamArg.ml [hunk 2]
```diff
@@ -1525,8 +1528,14 @@ let pin ?(unpin_only=false) () =
...
+       If unset, is inferred from the format of the target, defaulting \
+       to $(i,path). If $(i,auto) or $(i,OPAMPINKINDAUTO) is set, a local \
```
Comment (dbuenzli) [inline src/client/opamArg.ml]: `OPAMPINKINDAUTO` should be mentioned [here](https://github.com/ocaml/opam/blob/master/src/client/opamArg.ml#L227).

File: src/client/opamArg.ml (hunk 1 above)
Comment (AltGr) [inline src/client/opamArg.ml]: Nice, thanks! I missed that indeed :)
