### PR TITLE
opam var fixes

### LINKED ISSUE #4182: opam var package var not found
`opam config var` find the `installed` variable value, but not `opam var`
```
% opam var ocp-index:installed
[ERROR] Variable ocp-index:installed not found

% opam config var ocp-index:installed
true
```

### LINKED ISSUE #4183: opam var changes
opam var don't permit global variables lookup when no scope is given.

related to https://github.com/ocaml/opam-depext/issues/124

(from https://github.com/ocaml/opam-depext/issues/124#issuecomment-624606338)
>  `opam config var` remained unchanged, but `opam var` need to act on a scope, and default is switch, while arch is a global variable.

### PR DESCRIPTION
**Pull request by rjbou**
* No scope needed for variable display (as 2.0 opam var) fix #4183
* Fix package variable display fix #4182 
* Not found message include scope

### CODE REVIEW

File: src/client/opamConfigCommand.ml [hunk 1]
```diff
@@ -933,18 +933,22 @@ let option_show_switch gt ?st field =
...
   | Some c ->
     OpamConsole.msg "%s\n" (OpamVariable.string_of_variable_contents c)
   | None ->
-    OpamConsole.error_and_exit `Not_found "Variable %s not found" v
+    OpamConsole.error_and_exit `Not_found "Variable %s not found in %s" v
+      (match switch with
+           | None -> "global config"
+           | Some switch -> "in switch " ^ (OpamSwitch.to_string switch))
 
 let is_switch_defined_var switch_config v =
```
Comment (rjbou) [inline src/client/opamConfigCommand.ml:946]: Should we move this function into `OpamPackageVar` ?

**Comment by kit-ty-kate** [comment]
This PR doesn't seem to fix an issue that arise for packages that uses `opam config var` when during compilation. For instance:
```
#=== ERROR while compiling ocaml-freestanding.0.6.0 ===========================#
# context     2.1.0~alpha | linux/x86_64 | ocaml-variants.4.11.0+trunk | pinned(https://github.com/mirage/ocaml-freestanding/archive/v0.6.0.tar.gz)
# path        ~/.opam/4.11/.opam-switch/build/ocaml-freestanding.0.6.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/ocaml-freestanding-3440035-e7966f.env
# output-file ~/.opam/log/ocaml-freestanding-3440035-e7966f.out
### output ###
# ./configure.sh
# Fatal error:
# opam: "open" failed on /home/kit_ty_kate/.opam/log/log-3441455-4438d8.out: Read-only file system
```
the configure script uses `opam config var prefix` and thus fails when this command tries to create a log file

**Comment by rjbou** [comment]
@kit-ty-kate are you in the case of #4188?

**Comment by kit-ty-kate** [comment]
That seems to be the case (`.opam` directory upgraded from opam 2.0.7)

File: src/client/opamCommands.ml [hunk 2]
```diff
@@ -869,6 +869,16 @@ module Var_Option_Common = struct
...
       `Ok ()
+    | `All_var ->
+      (match apply with
+       | `value_wo_eq v ->
+         OpamGlobalState.with_ `Lock_none @@ fun gt ->
+         OpamConfigCommand.var_show gt v;
+         `Ok ()
+       | `empty -> assert false (* can't happen *)
+       | `value_eq _ ->
+         `Error (true, "variable setting needs a scope, \
```
Comment (rjbou) [inline src/client/opamCommands.ml:880]: This restriction is only for `opam var` affectations, should we set switch scope by default ?

Comment (rjbou) [reply src/client/opamCommands.ml:880]: After some discussions, no for variables
