### PR TITLE
More clear message for pinned package update that have local changes

### LINKED ISSUE #5294: `--working-dir` option does not work when calling `opam update`
Similar to https://github.com/ocaml/opam/issues/3807

On opam `2.1.3` on macos I observe the following behavior when trying to update a switch with some package pinned from directories:

```
❯ opam update --working-dir
<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><>  🐫 
[default] synchronised from https://opam.ocaml.org

<><> Synchronising development packages <><><><><><><><><><><><><><><><><><>  🐫 
[NOTE] Ignoring uncommitted changes in /Users/ulysse/tmp/dune (`--working-dir' not active).
```

I also observe unexpected behaviour when specifying the package to update:
```
❯ opam update dune
<><> Synchronising development packages <><><><><><><><><><><><><><><><><><>  🐫 
[NOTE] Ignoring uncommitted changes in /Users/ulysse/tmp/dune (`--working-dir' not active).
[dune.dev] synchronised (no changes)

❯ opam update --working-dir dune
<><> Synchronising development packages <><><><><><><><><><><><><><><><><><>  🐫 
Processing  1/1: [dune.dev: git]
[dune.dev] fetching sources failed: /Users/ulysse/tmp/dune/
```

### PR DESCRIPTION
**Pull request by rjbou**
When no working dir given, or no arguments specified 
fix #5294

### CODE REVIEW

File: src/state/opamUpdate.ml [hunk 1]
```diff
@@ -273,7 +273,8 @@ let pinned_package st ?version ?(autolock=false) ?(working_dir=false) name =
          OpamRepository.is_dirty ?subpath url
          @@| function false -> () | true ->
            OpamConsole.note
-             "Ignoring uncommitted changes in %s%s (`--working-dir' not active)."
+             "Ignoring uncommitted changes in %s%s \
+              (`--working-dir' not active, not given or with no argument)."
```
Comment (dra27) [inline src/state/opamUpdate.ml:277]:
```suggestion
              (`--working-dir' not specified or specified with no argument)."
```

??
